begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('de620000-0000-0000-0000-000000000001','quote-inquiry@test.example');
set local role authenticated;
select set_config('request.jwt.claim.sub','de620000-0000-0000-0000-000000000001',true);
create temporary table qi_ids as select gen_random_uuid() q,gen_random_uuid() i;
insert into romiku_quotes(id,counterparty_snapshot,notes) select q,'{"company_name":"QI Snapshot"}','QIRegression20261006' from qi_ids;
insert into romiku_quote_items(quote_id,sku,quantity,unit_price,product_snapshot) select q,'QI-SKU',2,9,'{"name":"Saved product"}' from qi_ids;
insert into romiku_website_inquiries(id,customer_name,email,whatsapp,message,raw_payload) select i,'QIRegression20261006','qiregression@example.test','+57 300 123 4567','Original message','{"preserve":true}' from qi_ids;
create temporary table qi_before as select (select counterparty_snapshot from romiku_quotes where id=q) buyer,(select product_snapshot from romiku_quote_items where quote_id=q) product,(select raw_payload from romiku_website_inquiries where id=i) raw from qi_ids;
select is((select status from romiku_quotes where id=(select q from qi_ids)),'pending_quote','Quote defaults pending_quote');
select is((select status from romiku_website_inquiries where id=(select i from qi_ids)),'pending_screening','Inquiry defaults pending_screening');
-- Real UPDATE path used by List/Detail, followed by the existing bulk path.
select lives_ok(format('update public.romiku_quotes set status=%L where id=%L',v,(select q from qi_ids)),'Quote direct update '||v) from unnest(array['quoted','following_up','customer_no_reply','following_up','won','invalid','pending_quote']) v;
select is(romiku_batch_status('quote',array[(select q from qi_ids)],v)->>'ok','true','Quote bulk update '||v) from unnest(array['pending_quote','quoted','following_up','customer_no_reply','won','invalid']) v;
select is((select status from romiku_quotes where id=(select q from qi_ids)),'invalid','Quote final status persisted');
update romiku_quotes set status='sent' where id=(select q from qi_ids);
select is((select status from romiku_quotes where id=(select q from qi_ids)),'quoted','stale sent write maps to quoted');
select is(romiku_batch_status('quote',array[(select q from qi_ids)],'sent')->>'code','INVALID_STATUS','old Quote status excluded from batch choices');
select throws_ok($$update romiku_quotes set status='mystery' where id=(select q from qi_ids)$$,'23514',null,'unknown Quote status rejected');
select is(romiku_global_search('QIRegression20261006',array['quote'],25,0,'{"status":"quoted"}')->'groups'->0->>'total_count','1','Quote status filtering occurs server-side');
select is(romiku_global_search('QIRegression20261006',array['quote'],25,0,'{"status":"won"}')->'groups'->0->>'total_count','0','Quote status filter excludes other statuses');
select lives_ok(format('update public.romiku_website_inquiries set status=%L where id=%L',v,(select i from qi_ids)),'Inquiry single update '||v) from unnest(array['pending_screening','pending_contact','pending_quote','quoted','following_up','customer_no_reply','won','invalid']) v;
select is(romiku_batch_status('website_inquiry',array[(select i from qi_ids)],v)->>'ok','true','Inquiry bulk update '||v) from unnest(array['pending_screening','pending_contact','pending_quote','quoted','following_up','customer_no_reply','won','invalid']) v;
select is(romiku_global_search('573001234567',array['website_inquiry'],25,0,'{"status":"invalid"}')->'groups'->0->>'total_count','1','normalized WhatsApp with server status filter');
select is(romiku_global_search('qiregression@example.test',array['website_inquiry'],25,0,'{"status":"invalid"}')->'groups'->0->>'total_count','1','Inquiry email searchable');
select is((select counterparty_snapshot from romiku_quotes where id=(select q from qi_ids)),(select buyer from qi_before),'Quote status preserves buyer snapshot');
select is((select product_snapshot from romiku_quote_items where quote_id=(select q from qi_ids)),(select product from qi_before),'Quote status preserves product snapshot');
select is((select quantity*unit_price from romiku_quote_items where quote_id=(select q from qi_ids)),18::numeric,'Quote prices unchanged');
select is((select raw_payload from romiku_website_inquiries where id=(select i from qi_ids)),(select raw from qi_before),'Inquiry status preserves raw payload');
select is((select message from romiku_website_inquiries where id=(select i from qi_ids)),'Original message','Inquiry message unchanged');
select throws_ok($$update romiku_website_inquiries set message='corrupted' where id=(select i from qi_ids)$$,'23514',null,'original submission stays immutable');
reset role;
set local role service_role;
create temporary table qi_payload as select '{"customerName":"QI API","email":"qiregression@example.test","country":"Colombia","message":"Original","items":[{"sku":"QI","quantity":1,"requirement":""}]}'::jsonb value;
create temporary table qi_intake as select * from romiku_submit_website_inquiry((select value from qi_payload));
select is((select whatsapp from romiku_website_inquiries where id=(select id from qi_intake)),null::text,'legacy intake without WhatsApp accepted as NULL');
select lives_ok($$select romiku_submit_website_inquiry((select value||'{"whatsapp":null}' from qi_payload))$$,'explicit null WhatsApp accepted');
select lives_ok($$select romiku_submit_website_inquiry((select value||'{"whatsapp":"   "}' from qi_payload))$$,'blank WhatsApp accepted');
create temporary table qi_phone as select * from romiku_submit_website_inquiry((select value||'{"whatsapp":"  +57 300 123 4567  "}' from qi_payload));
select is((select whatsapp from romiku_website_inquiries where id=(select id from qi_phone)),'+57 300 123 4567','WhatsApp trims edges and preserves plus/country/format');
select is((select raw_payload->>'whatsapp' from romiku_website_inquiries where id=(select id from qi_phone)),'  +57 300 123 4567  ','raw payload kept exactly as submitted');
select throws_ok($$select romiku_submit_website_inquiry((select value||'{"whatsapp":573001234567}' from qi_payload))$$,'22023',null,'numeric WhatsApp rejected');
reset role;
select * from finish();
rollback;
