begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_column('public','romiku_website_inquiries','submission_id','submission UUID supported');
select has_column('public','romiku_quote_items','requested_quantity_snapshot','independent request quantity supported');
create temp table final_payload as select '{"submissionId":"bdb96dfb-e4eb-48f8-839c-85e5200f0001","customerName":"Buyer Original","company":"ABC Nails","brand":"Snapshot Brand","email":"qa@example.test","whatsapp":"+57 300 123 4567","country":"Colombia","message":"Original request","items":[{"sku":"SUN5","productName":"Saved Lamp","image":"https://romiku.com/images/products-local/sun5.jpg","specification":"Saved 48W","unit":"pcs","cartonQty":32,"cartonCbm":0.125,"quantity":120.1234,"requirement":"White"},{"sku":"G03","productName":"Saved Gel","image":"","specification":"15ml","quantity":600,"requirement":""}]}'::jsonb p;
grant select on final_payload to service_role,authenticated;
set local role service_role;
select set_config('request.jwt.claim.sub','',true);
create temp table final_first as select * from romiku_submit_website_inquiry((select p from final_payload));
select is((select string_agg(sku,',' order by position) from romiku_website_inquiry_items where inquiry_id=(select id from final_first)),'SUN5,G03','saved item order follows submission');
select is((select replay from final_first),false,'first receipt is new');
create temp table final_retry as select * from romiku_submit_website_inquiry((select jsonb_set(p,'{items,0,quantity}','999')||'{"company":"changed"}' from final_payload));
select is((select id from final_retry),(select id from final_first),'same submission returns same WI');
select is((select replay from final_retry),true,'second receipt replay');
select is((select "normalizedSubmission" from final_retry),(select p from final_payload),'replay returns original snapshot');
select is((select submitted_at from final_retry),(select submitted_at from final_first),'replay retains original date');
select is((select count(*) from romiku_status_history where resource_id=(select id from final_first)),1::bigint,'retry creates no second history');
select is((select quantity from romiku_website_inquiry_items where inquiry_id=(select id from final_first) and sku='SUN5'),120.1234::numeric,'quantity precision retained');
select is((select product_snapshot->>'name' from romiku_website_inquiry_items where inquiry_id=(select id from final_first) and sku='SUN5'),'Saved Lamp','product canonical name saved');
select is((select product_snapshot->>'image_url' from romiku_website_inquiry_items where inquiry_id=(select id from final_first) and sku='SUN5'),'https://romiku.com/images/products-local/sun5.jpg','authoritative image saved');
select is((select brand from romiku_website_inquiries where id=(select id from final_first)),'Snapshot Brand','brand saved');
select is((select source from romiku_website_inquiries where id=(select id from final_first)),'website','source fixed');
select is((select owner_id from romiku_website_inquiries where id=(select id from final_first)),null::uuid,'unassigned');
select is((select formal_customer_id from romiku_website_inquiries where id=(select id from final_first)),null::uuid,'no automatic customer');
create temp table final_other as select * from romiku_submit_website_inquiry((select p||'{"submissionId":"bdb96dfb-e4eb-48f8-839c-85e5200f0002"}' from final_payload));
select isnt((select id from final_other),(select id from final_first),'same email different submission is distinct');
select throws_ok($$update romiku_website_inquiries set brand='tampered' where id=(select id from final_first)$$,'23514',null,'brand immutable');
select throws_ok($$update romiku_website_inquiry_items set product_snapshot='{}' where inquiry_id=(select id from final_first)$$,'23514',null,'new product snapshots immutable');
select throws_ok($$select romiku_submit_website_inquiry((select (p||'{"submissionId":"bdb96dfb-e4eb-48f8-839c-85e5200f0004"}') #- '{items,0,productName}' from final_payload))$$,'22023',null,'RPC independently validates full snapshot');
select throws_ok($$select romiku_submit_website_inquiry((select jsonb_set(p||'{"submissionId":"bdb96dfb-e4eb-48f8-839c-85e5200f0004"}','{items,0,image}','"data:image/png;base64,AA"') from final_payload))$$,'22023',null,'RPC rejects base64 snapshot');
select throws_ok($$update romiku_website_inquiries set submission_id=gen_random_uuid() where id=(select id from final_first)$$,'23514',null,'submission identity immutable');
select lives_ok($$select romiku_submit_website_inquiry((select jsonb_set(jsonb_set(p||'{"submissionId":"bdb96dfb-e4eb-48f8-839c-85e5200f0005"}','{items,0,cartonQty}','null'),'{items,0,cartonCbm}','null') from final_payload))$$,'unknown packing may be null');
select is((select product_snapshot ? 'cartonQty' from romiku_website_inquiry_items where sku='SUN5' and inquiry_id=(select id from romiku_website_inquiries where submission_id='bdb96dfb-e4eb-48f8-839c-85e5200f0005')),false,'unknown packing remains absent in canonical snapshot');
reset role;
insert into auth.users(id,email) values('bdb96dfb-e4eb-48f8-839c-85e5200f0003','final-chain@example.test');
grant select on final_first to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','bdb96dfb-e4eb-48f8-839c-85e5200f0003',true);
create temp table final_quote as select romiku_quote_from_inquiry((select id from final_first),(select array_agg(id order by sku) from romiku_website_inquiry_items where inquiry_id=(select id from final_first))) id;
select is((select status from romiku_quotes where id=(select id from final_quote)),'pending_quote','created Quote pending quote');
select is((select status from romiku_website_inquiries where id=(select id from final_first)),'pending_screening','conversion does not change Inquiry status');
select is((select requested_quantity_snapshot from romiku_quote_items where quote_id=(select id from final_quote) and sku='SUN5'),120.1234::numeric,'conversion saves requested quantity');
select is((select packing_snapshot->>'qty_per_carton' from romiku_quote_items where quote_id=(select id from final_quote) and sku='SUN5'),'32','packing copied');
select is((select counterparty_snapshot->>'brand' from romiku_quotes where id=(select id from final_quote)),'Snapshot Brand','buyer brand copied');
select is((select counterparty_snapshot->>'contact_name' from romiku_quotes where id=(select id from final_quote)),'Buyer Original','contact copied');
select is(romiku_global_search('Snapshot Brand',array['website_inquiry'],25,0,'{}')->'groups'->0->>'total_count','3','brand indexed search includes inquiries');
update romiku_quote_items set quantity=240, product_snapshot=product_snapshot||'{"name":"Quoted name"}' where quote_id=(select id from final_quote) and sku='SUN5';
select is((select requested_quantity_snapshot from romiku_quote_items where quote_id=(select id from final_quote) and sku='SUN5'),120.1234::numeric,'commercial editing preserves requested quantity');
select is((select quantity from romiku_website_inquiry_items where inquiry_id=(select id from final_first) and sku='SUN5'),120.1234::numeric,'editing Quote never writes Inquiry');
select throws_ok($$update romiku_quote_items set requested_quantity_snapshot=5 where quote_id=(select id from final_quote)$$,'23514',null,'requested quantity cannot be edited');
create temp table direct_quote as with q as(insert into romiku_quotes(notes) values('direct') returning id) select id from q;
insert into romiku_quote_items(quote_id,sku,quantity) select id,'DIRECT',1 from direct_quote;
select is((select requested_quantity_snapshot from romiku_quote_items where quote_id=(select id from direct_quote)),null::numeric,'direct quote quantity snapshot is NULL');
select throws_ok($$update romiku_quote_items set source_website_inquiry_item_id=null where quote_id=(select id from final_quote)$$,'23514',null,'saved requested quantity source cannot be detached');
select throws_ok($$update romiku_quote_items set quote_id=(select id from direct_quote) where quote_id=(select id from final_quote)$$,'23514',null,'saved requested quantity cannot move to unrelated Quote');

select throws_ok($$update romiku_quotes set source_website_inquiry_id=null where id=(select id from final_quote)$$,'23514',null,'website Quote source cannot be detached');
select throws_ok($$update romiku_quotes set source_website_inquiry_id=(select id from romiku_website_inquiries where submission_id='bdb96dfb-e4eb-48f8-839c-85e5200f0002') where id=(select id from final_quote)$$,'23514',null,'website Quote source cannot be rebound');
select throws_ok($$update romiku_quotes set source_website_inquiry_id=(select id from final_first) where id=(select id from direct_quote)$$,'23514',null,'direct Quote cannot acquire fake website provenance');
select lives_ok($$update romiku_quotes set notes='Updated quote note',status='following_up',source_website_inquiry_id=source_website_inquiry_id where id=(select id from final_quote)$$,'ordinary Quote edits and unchanged source remain allowed');
select is((select source_website_inquiry_id from romiku_quotes where id=(select id from final_quote)),(select id from final_first),'source survives ordinary Quote editing');
select throws_ok($$insert into romiku_quote_items(quote_id,sku,quantity,requested_quantity_snapshot) select id,'FAKE',1,1 from direct_quote$$,'23514',null,'direct requested quantity cannot be forged');
-- Even a privileged historical correction cannot change an existing Quote snapshot.
reset role;
alter table romiku_website_inquiry_items disable trigger romiku_original;
update romiku_website_inquiry_items set quantity=240 where inquiry_id=(select id from final_first) and sku='SUN5';
alter table romiku_website_inquiry_items enable trigger romiku_original;
select is((select requested_quantity_snapshot from romiku_quote_items where quote_id=(select id from final_quote) and sku='SUN5'),120.1234::numeric,'later source correction does not alter Quote');
select * from finish();
rollback;
