begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_function('public','romiku_global_search',array['text','text[]','integer','integer','jsonb'],'business search RPC exists');
insert into auth.users(id,email,raw_user_meta_data) values ('5ea00000-0000-0000-0000-000000000001','search-test@example.test','{}');
select ok(not prosecdef and proconfig @> array['search_path=""'],'invoker with fixed search_path') from pg_proc where oid='public.romiku_global_search(text,text[],integer,integer,jsonb)'::regprocedure;
select ok(not has_function_privilege('anon','public.romiku_global_search(text,text[],integer,integer,jsonb)','execute'),'anon denied');
set local role anon;
select throws_ok($$select public.romiku_global_search('x')$$,'42501',null,'anon RPC denied');
reset role;
set local role authenticated;
select throws_ok($$select public.romiku_global_search('x')$$,'42501',null,'missing auth uid denied');
select set_config('request.jwt.claim.sub','5ea00000-0000-0000-0000-000000000001',true);
create temporary table search_ids(kind text primary key,id uuid default gen_random_uuid());
insert into search_ids(kind) values ('formal_customer'),('outbound'),('website_inquiry'),('quote'),('pi'),('order'),('production'),('packing');
insert into romiku_formal_customers(id,name,requirements,logistics) select id,'Searchfixture customer','{"packaging":"requirementneedle"}','{"receiving_phone":"+44 (20) 1234-9876"}' from search_ids where kind='formal_customer';
insert into romiku_outbound_companies(id,name,business_intelligence) select id,'Searchfixture outbound','{"operations":"operationneedle"}' from search_ids where kind='outbound';
insert into romiku_customer_contacts(formal_customer_id,name,email,phone) select id,'Contactneedle','contactneedle@example.test','+1 (212) 555-7890' from search_ids where kind='formal_customer';
insert into romiku_outbound_contacts(outbound_company_id,name,whatsapp) select id,'Outboundcontactneedle','+86 138-1234-5678' from search_ids where kind='outbound';
insert into romiku_website_inquiries(id,customer_name,message,processing_notes,raw_payload) select id,'Inquiry buyer','messageneedle','processingneedle','{"secret":"rawsecretneedle"}' from search_ids where kind='website_inquiry';
insert into romiku_website_inquiry_items(inquiry_id,sku,quantity,requirement,product_snapshot) select id,'INQ-SKU-NEEDLE',1,'inquiryrequirementneedle','{"name":"inquiryproductneedle"}' from search_ids where kind='website_inquiry';
insert into romiku_quotes(id,counterparty_snapshot,notes,archived_at) select id,'{"name":"Historicalneedle","phone":"+49 (30) 1234-5678","unexpected":"hiddenjsonneedle"}','headernotesneedle',now() from search_ids where kind='quote';
insert into romiku_quote_items(quote_id,sku,quantity,customer_code,requirement,notes,product_snapshot) select id,'OWN-QUOTE-SKU',1,'CustomerCodeNeedle','itemrequirementneedle','itemnotesneedle','{"name":"productnameneedle","description":"descriptionneedle","specification":"specificationneedle"}' from search_ids where kind='quote';
insert into romiku_pis(id,counterparty_snapshot,notes,archived_at) select id,'{"name":"Historicalneedle","phone":"+49 (30) 1234-5678","unexpected":"hiddenjsonneedle"}','headernotesneedle',now() from search_ids where kind='pi';
insert into romiku_pi_items(pi_id,sku,quantity,customer_code,requirement,notes,product_snapshot) select id,'OWN-PI-SKU',1,'CustomerCodeNeedle','itemrequirementneedle','itemnotesneedle','{"name":"productnameneedle","description":"descriptionneedle","specification":"specificationneedle"}' from search_ids where kind='pi';
insert into romiku_orders(id,counterparty_snapshot,notes,archived_at) select id,'{"name":"Historicalneedle","phone":"+49 (30) 1234-5678","unexpected":"hiddenjsonneedle"}','headernotesneedle',now() from search_ids where kind='order';
insert into romiku_order_items(order_id,sku,quantity,customer_code,requirement,notes,product_snapshot) select id,'OWN-ORDER-SKU',1,'CustomerCodeNeedle','itemrequirementneedle','itemnotesneedle','{"name":"productnameneedle","description":"descriptionneedle","specification":"specificationneedle"}' from search_ids where kind='order';
insert into romiku_order_items(order_id,sku,quantity,product_snapshot) select id,'SOURCE-ONLY-PRODUCT',1,'{"name":"sourceonlyproductneedle"}' from search_ids where kind='order';
insert into romiku_production_orders(id,order_id,name,supplier_snapshot,notes) select p.id,o.id,'Searchfixture production','{"name":"Savedfactoryneedle","phone":"+81 (3) 9876-5432"}','productionnotesneedle' from search_ids p,search_ids o where p.kind='production' and o.kind='order';
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity,product_snapshot,production_note_zh) select p.id,i.order_id,i.id,'OWN-PRODUCTION-SKU',1,'{"name":"productionproductneedle","customer_code":"productioncodeneedle","specification":"productionspecneedle","requirement":"productionrequirementneedle"}','productionnoteneedle' from search_ids p join romiku_order_items i on i.sku='OWN-ORDER-SKU' where p.kind='production';
insert into romiku_packing_lists(id,order_id,name,buyer_snapshot,seller_snapshot) select p.id,o.id,'Searchfixture packing','{"name":"Packingbuyerneedle"}','{"company_name":"Packingsellerneedle"}' from search_ids p,search_ids o where p.kind='packing' and o.kind='order';
insert into romiku_packing_items(packing_list_id,sku,quantity,product_snapshot,remark) select id,'OWN-PACKING-SKU',1,'{"name":"packingproductneedle","unit":"UnitNeedle"}','packingremarkneedle' from search_ids where kind='packing';
update romiku_website_inquiries set document_number='SEARCHFIXTURE-INQ' where id=(select id from search_ids where kind='website_inquiry');
update romiku_quotes set document_number='SEARCHFIXTURE-QUOTE' where id=(select id from search_ids where kind='quote');
update romiku_pis set document_number='SEARCHFIXTURE-PI' where id=(select id from search_ids where kind='pi');
update romiku_orders set document_number='SEARCHFIXTURE-ORDER' where id=(select id from search_ids where kind='order');
create function pg_temp.search_group(q text,t text, lim integer default 25, off integer default 0, f jsonb default '{}') returns jsonb language sql as $$select public.romiku_global_search(q,array[t],lim,off,f)->'groups'->0$$;
select is(jsonb_array_length(public.romiku_global_search('')->'groups'),8,'empty query preserves all eight groups');
select is((pg_temp.search_group('','quote')->>'total_count')::int,0,'empty query returns no matches');
select is((pg_temp.search_group('   ','quote')->>'total_count')::int,0,'whitespace query returns no matches');
select is((pg_temp.search_group('searchfixture','formal_customer')->>'total_count')::int,1,'case insensitive formal_customer header');
select is((pg_temp.search_group('searchfixture','outbound')->>'total_count')::int,1,'case insensitive outbound header');
select is((pg_temp.search_group('searchfixture','website_inquiry')->>'total_count')::int,1,'case insensitive website_inquiry header');
select is((pg_temp.search_group('searchfixture','quote')->>'total_count')::int,1,'case insensitive quote header');
select is((pg_temp.search_group('searchfixture','pi')->>'total_count')::int,1,'case insensitive pi header');
select is((pg_temp.search_group('searchfixture','order')->>'total_count')::int,1,'case insensitive order header');
select is((pg_temp.search_group('searchfixture','production')->>'total_count')::int,1,'case insensitive production header');
select is((pg_temp.search_group('searchfixture','packing')->>'total_count')::int,1,'case insensitive packing header');
select is((pg_temp.search_group('requirementneedle','formal_customer')->>'total_count')::int,1,'formal_customer matches requirementneedle');
select is((pg_temp.search_group('442012349876','formal_customer')->>'total_count')::int,1,'formal_customer matches 442012349876');
select is((pg_temp.search_group('Contactneedle','formal_customer')->>'total_count')::int,1,'formal_customer matches Contactneedle');
select is((pg_temp.search_group('12125557890','formal_customer')->>'total_count')::int,1,'formal_customer matches 12125557890');
select is((pg_temp.search_group('+1-212-555-7890','formal_customer')->>'total_count')::int,1,'formal_customer matches +1-212-555-7890');
select is((pg_temp.search_group('operationneedle','outbound')->>'total_count')::int,1,'outbound matches operationneedle');
select is((pg_temp.search_group('Outboundcontactneedle','outbound')->>'total_count')::int,1,'outbound matches Outboundcontactneedle');
select is((pg_temp.search_group('8613812345678','outbound')->>'total_count')::int,1,'outbound matches 8613812345678');
select is((pg_temp.search_group('messageneedle','website_inquiry')->>'total_count')::int,1,'website_inquiry matches messageneedle');
select is((pg_temp.search_group('processingneedle','website_inquiry')->>'total_count')::int,1,'website_inquiry matches processingneedle');
select is((pg_temp.search_group('inquiryrequirementneedle','website_inquiry')->>'total_count')::int,1,'website_inquiry matches inquiryrequirementneedle');
select is((pg_temp.search_group('inquiryproductneedle','website_inquiry')->>'total_count')::int,1,'website_inquiry matches inquiryproductneedle');
select is((pg_temp.search_group('INQ-SKU-NEEDLE','website_inquiry')->>'total_count')::int,1,'website_inquiry matches INQ-SKU-NEEDLE');
select is((pg_temp.search_group('Historicalneedle','quote')->>'total_count')::int,1,'quote matches Historicalneedle');
select is((pg_temp.search_group('493012345678','quote')->>'total_count')::int,1,'quote matches 493012345678');
select is((pg_temp.search_group('headernotesneedle','quote')->>'total_count')::int,1,'quote matches headernotesneedle');
select is((pg_temp.search_group('OWN-QUOTE-SKU','quote')->>'total_count')::int,1,'quote matches OWN-QUOTE-SKU');
select is((pg_temp.search_group('CustomerCodeNeedle','quote')->>'total_count')::int,1,'quote matches CustomerCodeNeedle');
select is((pg_temp.search_group('itemrequirementneedle','quote')->>'total_count')::int,1,'quote matches itemrequirementneedle');
select is((pg_temp.search_group('itemnotesneedle','quote')->>'total_count')::int,1,'quote matches itemnotesneedle');
select is((pg_temp.search_group('productnameneedle','quote')->>'total_count')::int,1,'quote matches productnameneedle');
select is((pg_temp.search_group('descriptionneedle','quote')->>'total_count')::int,1,'quote matches descriptionneedle');
select is((pg_temp.search_group('specificationneedle','quote')->>'total_count')::int,1,'quote matches specificationneedle');
select is((pg_temp.search_group('OWN-PI-SKU','pi')->>'total_count')::int,1,'pi matches OWN-PI-SKU');
select is((pg_temp.search_group('OWN-ORDER-SKU','order')->>'total_count')::int,1,'order matches OWN-ORDER-SKU');
select is((pg_temp.search_group('Savedfactoryneedle','production')->>'total_count')::int,1,'production matches Savedfactoryneedle');
select is((pg_temp.search_group('81398765432','production')->>'total_count')::int,1,'production matches 81398765432');
select is((pg_temp.search_group('productionnotesneedle','production')->>'total_count')::int,1,'production matches productionnotesneedle');
select is((pg_temp.search_group('productionproductneedle','production')->>'total_count')::int,1,'production matches productionproductneedle');
select is((pg_temp.search_group('productioncodeneedle','production')->>'total_count')::int,1,'production matches productioncodeneedle');
select is((pg_temp.search_group('productionspecneedle','production')->>'total_count')::int,1,'production matches productionspecneedle');
select is((pg_temp.search_group('productionrequirementneedle','production')->>'total_count')::int,1,'production matches productionrequirementneedle');
select is((pg_temp.search_group('productionnoteneedle','production')->>'total_count')::int,1,'production matches productionnoteneedle');
select is((pg_temp.search_group('Historicalneedle','production')->>'total_count')::int,1,'production matches Historicalneedle');
select is((pg_temp.search_group('SEARCHFIXTURE-ORDER','production')->>'total_count')::int,1,'production matches SEARCHFIXTURE-ORDER');
select is((pg_temp.search_group('Packingbuyerneedle','packing')->>'total_count')::int,1,'packing matches Packingbuyerneedle');
select is((pg_temp.search_group('Packingsellerneedle','packing')->>'total_count')::int,1,'packing matches Packingsellerneedle');
select is((pg_temp.search_group('packingproductneedle','packing')->>'total_count')::int,1,'packing matches packingproductneedle');
select is((pg_temp.search_group('UnitNeedle','packing')->>'total_count')::int,1,'packing matches UnitNeedle');
select is((pg_temp.search_group('packingremarkneedle','packing')->>'total_count')::int,1,'packing matches packingremarkneedle');
select is((pg_temp.search_group('SEARCHFIXTURE-ORDER','packing')->>'total_count')::int,1,'packing matches SEARCHFIXTURE-ORDER');
select is((pg_temp.search_group('sourceonlyproductneedle','production')->>'total_count')::int,0,'production excludes source order product names');
select is((pg_temp.search_group('SOURCE-ONLY-PRODUCT','packing')->>'total_count')::int,0,'packing excludes source order SKU');
select is((pg_temp.search_group('rawsecretneedle','website_inquiry')->>'total_count')::int,0,'raw payload excluded');
select is((pg_temp.search_group('hiddenjsonneedle','quote')->>'total_count')::int,0,'unlisted snapshot keys excluded');
select is((pg_temp.search_group('x493012345678','quote')->>'total_count')::int,0,'alphanumeric query cannot widen to normalized phone');
select is((pg_temp.search_group('SEARCHFIXTURE-QUOTE','quote')->'items'->0->>'rank')::int,0,'exact document rank');
select is((pg_temp.search_group('OWN-QUOTE-SKU','quote')->'items'->0->>'rank')::int,0,'exact SKU rank');
select is((pg_temp.search_group('Historicalneedle','quote')->'items'->0->>'rank')::int,1,'exact identity rank');
select is((pg_temp.search_group('+49-30-1234-5678','quote')->'items'->0->>'rank')::int,1,'exact normalized phone rank');
select is((pg_temp.search_group('historical','quote')->'items'->0->>'rank')::int,2,'prefix rank');
select is((pg_temp.search_group('ricalneedle','quote')->'items'->0->>'rank')::int,3,'partial rank');
select ok(pg_temp.search_group('Historicalneedle','production')->'items'->0->'matched_fields' ? 'source_order.counterparty_snapshot.name','source channel labeled');
insert into romiku_quote_items(quote_id,sku,quantity) select id,'OWN-QUOTE-SKU',1 from search_ids where kind='quote';
select is((pg_temp.search_group('OWN-QUOTE-SKU','quote')->>'total_count')::int,1,'multiple item hits deduplicate header');
insert into romiku_quotes(notes,created_at) select 'paginationneedle', '2025-01-01'::timestamptz+n*interval '1 day' from generate_series(1,31) n;
select is((pg_temp.search_group('paginationneedle','quote')->>'total_count')::int,31,'count before pagination');
select is(jsonb_array_length(pg_temp.search_group('paginationneedle','quote')->'items'),25,'default per group page 25');
select is(pg_temp.search_group('paginationneedle','quote')->>'has_more','true','first page has more');
select is(jsonb_array_length(pg_temp.search_group('paginationneedle','quote',25,25)->'items'),6,'second page six');
select is(pg_temp.search_group('paginationneedle','quote',25,25)->>'has_more','false','last page no more');
select is(pg_temp.search_group('paginationneedle','quote')->'items'->0->>'id',(select id::text from romiku_quotes where notes='paginationneedle' order by created_at desc,id limit 1),'UUID breaks equal timestamp and rank ties');
select is((pg_temp.search_group('paginationneedle','quote',50,90)->>'total_count')::int,31,'offset beyond end preserves count');
select is((pg_temp.search_group('searchfixture','quote',25,0,'{"status":"not-a-status"}')->>'total_count')::int,0,'status filter before count');
select is((pg_temp.search_group('searchfixture','production',25,0,jsonb_build_object('order_id',(select id from search_ids where kind='order')))->>'total_count')::int,1,'order filter');
insert into romiku_quotes(notes) values (E'literal%needle literal_needle literal\\needle');
select is((pg_temp.search_group('%','quote')->>'total_count')::int,1,'percent literal');
select is((pg_temp.search_group('literal_needle','quote')->>'total_count')::int,1,'underscore literal');
select is((pg_temp.search_group(E'\\','quote')->>'total_count')::int,1,'backslash literal');
select is((pg_temp.search_group($q$'; select 1; --$q$,'quote')->>'total_count')::int,0,'SQL metacharacters literal');
update romiku_quotes set notes='generatedupdateneedle' where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('generatedupdateneedle','quote')->>'total_count')::int,1,'generated text updates immediately');
update romiku_order_items set product_snapshot='{"name":"changedsourceproduct"}' where sku='OWN-ORDER-SKU';
select is((pg_temp.search_group('productionproductneedle','production')->>'total_count')::int,1,'production keeps own historical product');
select is((pg_temp.search_group('changedsourceproduct','production')->>'total_count')::int,0,'source product updates cannot leak');
update romiku_formal_customers set name='Changedlivecustomer' where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('Historicalneedle','quote')->>'total_count')::int,1,'saved buyer remains searchable independent of live customers');
select throws_ok($$select public.romiku_global_search('x',array['unknown'])$$,'22023',null,'invalid type rejected');
select throws_ok($$select public.romiku_global_search('x',array[null::text])$$,'22023',null,'null type element rejected');
select throws_ok($$select public.romiku_global_search('x',null,0)$$,'22023',null,'zero limit rejected');
select throws_ok($$select public.romiku_global_search('x',null,51)$$,'22023',null,'excess limit rejected');
select throws_ok($$select public.romiku_global_search('x',null,25,-1)$$,'22023',null,'negative offset rejected');
select throws_ok($$select public.romiku_global_search('x',null,null)$$,'22023',null,'null limit rejected');
select throws_ok($$select public.romiku_global_search('x',null,25,0,'{"unknown":"x"}')$$,'22023',null,'unknown filter rejected');
select throws_ok($$select public.romiku_global_search('x',null,25,0,'[]')$$,'22023',null,'nonobject filter rejected');
select throws_ok($$select public.romiku_global_search('x',null,25,0,'{"order_id":"invalid"}')$$,'22023',null,'invalid uuid filter rejected');
select throws_ok($$select public.romiku_global_search('x',null,25,0,'{"status":2}')$$,'22023',null,'nonstring status rejected');
reset role;
create policy search_test_restriction on public.romiku_quotes as restrictive for select to authenticated using (document_number <> 'SEARCHFIXTURE-QUOTE');
set local role authenticated;
select is((pg_temp.search_group('SEARCHFIXTURE-QUOTE','quote')->>'total_count')::int,0,'caller header RLS enforced');
select is((pg_temp.search_group('OWN-QUOTE-SKU','quote')->>'total_count')::int,0,'caller RLS cannot be bypassed by item match');
reset role;
drop policy search_test_restriction on public.romiku_quotes;
set local role authenticated;
update romiku_quotes set counterparty_snapshot=jsonb_build_object('company','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.company coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('brand','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.brand coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('business_name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.business_name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('contact','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.contact coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('phone','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.phone coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('whatsapp','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.whatsapp coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('email','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.email coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('country','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.country coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('region','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.region coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('city','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.city coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('address','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.address coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('company_name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.company_name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('brand_name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.brand_name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('contact_name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.contact_name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('customer_name','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.customer_name coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('telephone','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.telephone coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('mobile','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.mobile coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('shipping_address','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.shipping_address coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('billing_address','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.billing_address coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('consignee','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.consignee coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('consignee_contact','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.consignee_contact coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('receiving_company','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.receiving_company coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('receiving_contact','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.receiving_contact coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('receiving_phone','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.receiving_phone coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('delivery_address','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.delivery_address coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('forwarder_address','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.forwarder_address coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quotes set counterparty_snapshot=jsonb_build_object('tax_information','fieldmatrixneedle') where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit counterparty_snapshot.tax_information coverage');
update romiku_quotes set counterparty_snapshot='{}' where id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('sku','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.sku coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('customer_code','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.customer_code coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('name','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.name coverage');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->'items'->0->>'rank')::int,2,'product name exact is not identity');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('name_zh','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.name_zh coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('name_en','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.name_en coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('name_es','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.name_es coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('description','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.description coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('description_zh','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.description_zh coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('description_en','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.description_en coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('description_es','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.description_es coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('specification','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.specification coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('specifications','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.specifications coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('spec','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.spec coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('requirement','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.requirement coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('requirements','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.requirements coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('notes','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.notes coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('unit','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.unit coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_quote_items set product_snapshot=jsonb_build_object('shipping_mark','fieldmatrixneedle') where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('fieldmatrixneedle','quote')->>'total_count')::int,1,'explicit product_snapshot.shipping_mark coverage');
update romiku_quote_items set product_snapshot='{}' where quote_id=(select id from search_ids where kind='quote');
update romiku_formal_customers set requirements=jsonb_build_object('packaging','fieldmatrixneedle') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('fieldmatrixneedle','formal_customer')->>'total_count')::int,1,'explicit requirements.packaging coverage');
update romiku_formal_customers set requirements='{}' where id=(select id from search_ids where kind='formal_customer');
update romiku_formal_customers set requirements=jsonb_build_object('shipping_marks','fieldmatrixneedle') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('fieldmatrixneedle','formal_customer')->>'total_count')::int,1,'explicit requirements.shipping_marks coverage');
update romiku_formal_customers set requirements='{}' where id=(select id from search_ids where kind='formal_customer');
update romiku_formal_customers set requirements=jsonb_build_object('product_labels','fieldmatrixneedle') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('fieldmatrixneedle','formal_customer')->>'total_count')::int,1,'explicit requirements.product_labels coverage');
update romiku_formal_customers set requirements='{}' where id=(select id from search_ids where kind='formal_customer');
update romiku_formal_customers set requirements=jsonb_build_object('packing_preference','fieldmatrixneedle') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('fieldmatrixneedle','formal_customer')->>'total_count')::int,1,'explicit requirements.packing_preference coverage');
update romiku_formal_customers set requirements='{}' where id=(select id from search_ids where kind='formal_customer');
update romiku_formal_customers set requirements=jsonb_build_object('shipping_documents','fieldmatrixneedle') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('fieldmatrixneedle','formal_customer')->>'total_count')::int,1,'explicit requirements.shipping_documents coverage');
update romiku_formal_customers set requirements='{}' where id=(select id from search_ids where kind='formal_customer');
update romiku_quotes set counterparty_snapshot='{"aliases":["AliasNeedle"],"saved_aliases":["SavedAliasNeedle"]}' where id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('AliasNeedle','quote')->>'total_count')::int,1,'saved alias arrays covered');
select is((pg_temp.search_group('SavedAliasNeedle','quote')->'items'->0->>'rank')::int,1,'saved alias exact identity rank');
update romiku_quote_items set product_snapshot='{"name":{"zh":"中文产品","en":"LocalizedNeedle","es":"Nombre"}}' where quote_id=(select id from search_ids where kind='quote');
select is((pg_temp.search_group('中文产品','quote')->>'total_count')::int,1,'explicit product locale text covered');
select is((pg_temp.search_group('LocalizedNeedle','quote')->'items'->0->>'rank')::int,2,'product name is prefix rank, not identity rank');
select is((pg_temp.search_group('paginationneedle','quote',50)->>'total_count')::int,31,'page count before deletion');
select is(public.romiku_delete_record('quote',(select id from romiku_quotes where notes='paginationneedle' order by id limit 1))->>'ok','true','controlled deletion of search hit');
select is((pg_temp.search_group('paginationneedle','quote',50)->>'total_count')::int,30,'deleted hit disappears immediately');
reset role;
alter table public.romiku_quotes disable trigger romiku_audit;
update public.romiku_quotes set created_at='2040-01-01' where id=(select id from public.romiku_quotes where notes='paginationneedle' order by id desc limit 1);
alter table public.romiku_quotes enable trigger romiku_audit;
set local role authenticated;
select is(pg_temp.search_group('paginationneedle','quote')->'items'->0->>'id',(select id::text from romiku_quotes where notes='paginationneedle' order by created_at desc,id limit 1),'newest row wins tie rank');
reset role;
create policy search_items_restriction on public.romiku_pi_items as restrictive for select to authenticated using (sku<>'OWN-PI-SKU');
create policy search_contacts_restriction on public.romiku_customer_contacts as restrictive for select to authenticated using (name<>'Contactneedle');
set local role authenticated;
select is((pg_temp.search_group('OWN-PI-SKU','pi')->>'total_count')::int,0,'item caller RLS enforced');
select is((pg_temp.search_group('Contactneedle','formal_customer')->>'total_count')::int,0,'contact caller RLS enforced');
update romiku_packing_lists set buyer_snapshot='{"tel_whatsapp":"+86 (190) 2577-7589"}',seller_snapshot='{"tel_whatsapp":"+49 (30) 1234-8765"}' where id=(select id from search_ids where kind='packing');
select is((pg_temp.search_group('8619025777589','packing')->>'total_count')::int,1,'saved buyer tel_whatsapp normalized');
select is((pg_temp.search_group('+49-30-1234-8765','packing')->'items'->0->>'rank')::int,1,'saved seller tel_whatsapp exact normalized rank');
update romiku_production_items set packaging_snapshot='{"notes":"PackagingNotesNeedle","shipping_mark":"PackagingMarkNeedle"}' where production_order_id=(select id from search_ids where kind='production');
select is((pg_temp.search_group('PackagingNotesNeedle','production')->>'total_count')::int,1,'own production packaging notes');
select is((pg_temp.search_group('PackagingMarkNeedle','production')->>'total_count')::int,1,'own production packaging mark');
update romiku_outbound_companies set brand_name='SourceBrandNeedle',city='SourceCityNeedle' where id=(select id from search_ids where kind='outbound');
update romiku_formal_customers set source_outbound_company_id=(select id from search_ids where kind='outbound') where id=(select id from search_ids where kind='formal_customer');
select is((pg_temp.search_group('SourceBrandNeedle','formal_customer')->>'total_count')::int,1,'formal directory source brand');
select is((pg_temp.search_group('SourceCityNeedle','formal_customer')->>'total_count')::int,1,'formal directory source city');
insert into romiku_outbound_followups(outbound_company_id,method,summary,notes) select id,'email','FollowupSummaryNeedle','FollowupNotesNeedle' from search_ids where kind='outbound';
select is((pg_temp.search_group('FollowupSummaryNeedle','outbound')->>'total_count')::int,1,'outbound followup summary');
select is((pg_temp.search_group('FollowupNotesNeedle','outbound')->>'total_count')::int,1,'outbound followup notes');
select is((pg_temp.search_group(E'+49\t(30) 1234-8765','packing')->'items'->0->>'rank')::int,1,'copied phone tab whitespace normalizes');
select is((pg_temp.search_group(E'\t\n','quote')->>'total_count')::int,0,'all whitespace empty');
reset role;
select * from finish();
rollback;
