begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values ('de600000-0000-0000-0000-000000000001','order-cascade@test.example');
select ok(has_function_privilege('authenticated','public.romiku_order_delete_preflight(uuid[])','execute'),'authenticated preflight');
select ok(not has_function_privilege('anon','public.romiku_order_delete_preflight(uuid[])','execute'),'anon cannot preflight');
select ok(not has_function_privilege('anon','public.romiku_batch_delete_orders(uuid[])','execute'),'anon cannot batch');
set local role authenticated;
select is(romiku_order_delete_preflight(array[gen_random_uuid()])->>'code','UNAUTHENTICATED','preflight requires uid');
select is(romiku_batch_delete_orders(array[gen_random_uuid()])->>'code','UNAUTHENTICATED','batch requires uid');
select set_config('request.jwt.claim.sub','de600000-0000-0000-0000-000000000001',true);
select is(romiku_order_delete_preflight('{}')->>'code','INVALID_ARGUMENT','empty selection rejected');
select is(romiku_batch_delete_orders(array_fill(gen_random_uuid(),array[101]))->>'code','INVALID_ARGUMENT','oversized batch rejected');
select throws_ok($$delete from romiku_orders where false$$,'42501',null,'header delete still denied');
create temporary table cases(label text primary key,id uuid default gen_random_uuid(),p uuid default gen_random_uuid(),item uuid default gen_random_uuid());
insert into cases(label) values ('pending1'),('pending2'),('cancelled'),('mixed'),('completed'),('received'),('unknown'),('archived'),('followup'),('packing'),('payment'),('late'),('rollback'),('independent');
insert into romiku_orders(id) select id from cases;
insert into romiku_order_items(id,order_id,sku,quantity) select item,id,'CASCADE',100 from cases;
insert into romiku_production_orders(id,order_id,status,archived_at) select p,id,case when label in ('cancelled','completed','received','unknown') then label else 'pending' end,case when label='archived' then now() end from cases where label<>'independent';
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity) select p,id,item,'CASCADE',10 from cases where label<>'independent';
insert into romiku_production_orders(order_id,status) select id,case when label='mixed' then 'in_production' else 'pending' end from cases where label in ('pending2','mixed','rollback');
insert into romiku_production_followups(production_order_id,method,summary) select p,'email','keep followup' from cases where label='followup';
insert into romiku_packing_lists(order_id) select id from cases where label='packing';
insert into romiku_packing_lists(notes) values ('independent must not block unrelated order');
insert into romiku_payments(order_id,kind,amount) select id,'deposit',5 from cases where label='payment';
insert into romiku_manual_tasks(title,order_id) select 'retain order task '||label,id from cases where label in ('pending1','rollback');
insert into romiku_manual_tasks(title,production_order_id) select 'retain production task '||label,p from cases where label in ('pending1','rollback');
create temporary table preview as select romiku_order_delete_preflight(array_agg(id)) value from cases;
select is(jsonb_array_length(value->'deletable'),6,'six eligible orders, including cancelled and independent') from preview;
select is(jsonb_array_length(value->'blocked'),8,'executed, archived, followup, packing, payment blocked') from preview;
select is((select x->>'delete_mode' from preview,jsonb_array_elements(value->'deletable') x where x->>'order_id'=(select id::text from cases where label='pending2')),'cascade_production','cascade mode explicit');
select is((select jsonb_array_length(x->'cascade_productions') from preview,jsonb_array_elements(value->'deletable') x where x->>'order_id'=(select id::text from cases where label='pending2')),2,'all child business documents listed');
select is(romiku_delete_record('order',(select id from cases where label='mixed'))->>'code','HAS_DOWNSTREAM','mixed blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='completed'))->>'code','HAS_DOWNSTREAM','completed blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='received'))->>'code','HAS_DOWNSTREAM','received blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='unknown'))->>'code','HAS_DOWNSTREAM','unknown blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='archived'))->>'code','HAS_DOWNSTREAM','archived blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='followup'))->>'code','HAS_DOWNSTREAM','followup blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='packing'))->>'code','HAS_DOWNSTREAM','packing blocks single deletion');
select is(romiku_delete_record('order',(select id from cases where label='payment'))->>'code','HAS_DOWNSTREAM','payment blocks single deletion');
-- Recheck after preflight, per-order isolation within batch.
insert into romiku_payments(order_id,kind,amount) select id,'balance',1 from cases where label='late';
create temporary table batch as select romiku_batch_delete_orders(array_agg(id)) value from cases where label in ('pending1','pending2','cancelled','late','independent');
select is(jsonb_array_length(value->'deleted'),4,'eligible orders deleted together') from batch;
select is(value->'failed'->0->>'status','blocked_at_execution','new dependency rechecked') from batch;
select ok(exists(select 1 from romiku_orders where id=(select id from cases where label='late')),'late blocked order retained');
select is((select count(*) from romiku_production_orders where order_id in (select id from cases where label in ('pending1','pending2','cancelled'))),0::bigint,'pending and cancelled headers removed');
select is((select count(*) from romiku_order_items where order_id in (select id from cases where label in ('pending1','pending2','cancelled'))),0::bigint,'own order items removed');
select ok(exists(select 1 from romiku_manual_tasks where title='retain order task pending1' and order_id is null),'manual Order task retained and detached');
select ok(exists(select 1 from romiku_manual_tasks where title='retain production task pending1' and production_order_id is null),'manual Production task retained and detached');
reset role;
select is((select last_value from romiku_production_order_counters where order_id=(select id from cases where label='pending2')),2,'counter survives deleted Order without recycling');
create function public.cascade_test_failure() returns trigger language plpgsql as $$ begin if old.id=(select id from cases where label='rollback') then raise exception 'private FK details'; end if; return old; end $$;
create trigger cascade_test_failure before delete on romiku_orders for each row execute function public.cascade_test_failure();
set local role authenticated;
select is(romiku_delete_record('order',(select id from cases where label='rollback'))->>'code','DELETE_FAILED','late Order failure is structured');
select is((select count(*) from romiku_production_orders where order_id=(select id from cases where label='rollback')),2::bigint,'late failure rolls back both production deletes');
select is((select count(*) from romiku_production_items where order_id=(select id from cases where label='rollback')),1::bigint,'rollback restores production items');
select ok(exists(select 1 from romiku_manual_tasks where title='retain production task rollback' and production_order_id is not null),'rollback restores detached production task');
select ok(exists(select 1 from romiku_manual_tasks where title='retain order task rollback' and order_id is not null),'rollback restores detached order task');
select is(jsonb_array_length(romiku_batch_delete_orders(array[(select id from cases where label='rollback')])->'failed'),1,'batch reports failed transaction');
reset role;
select ok(not has_function_privilege('authenticated','public.romiku_delete_order_controlled(uuid)','execute'),'internal mutation helper not callable');
select ok(not has_function_privilege('authenticated','public.romiku_order_delete_eligibility(uuid)','execute'),'internal eligibility not callable');
select ok(bool_and(prosecdef and proconfig @> array['search_path=""']), 'new RPCs and helpers fixed search_path/security definer') from pg_proc where proname in ('romiku_delete_order_controlled','romiku_order_delete_eligibility','romiku_order_delete_preflight','romiku_batch_delete_orders');
set local role anon;
select throws_ok($$select public.romiku_order_delete_preflight(array[gen_random_uuid()])$$,'42501',null,'anon preflight actually denied');
select throws_ok($$select public.romiku_batch_delete_orders(array[gen_random_uuid()])$$,'42501',null,'anon execution actually denied');
reset role;
set local role authenticated;
select is(romiku_order_delete_preflight(array[null::uuid])->>'code','INVALID_ARGUMENT','null id rejected');
select is(romiku_order_delete_preflight(array[gen_random_uuid()])->'blocked'->0->>'code','NOT_FOUND','missing Order structured');
select is(jsonb_array_length(romiku_order_delete_preflight(array[(select id from cases where label='mixed'),(select id from cases where label='mixed')])->'blocked'),1,'duplicate IDs deduplicated');
insert into cases(label) values ('late_status'),('late_followup'),('late_archive'),('late_pack'),('batch_survivor');
insert into romiku_orders(id) select id from cases where label like 'late_%' or label='batch_survivor';
insert into romiku_production_orders(id,order_id) select p,id from cases where label like 'late_%';
select is(jsonb_array_length(romiku_order_delete_preflight(array(select id from cases where label like 'late_%'))->'deletable'),4,'all late-change fixtures initially eligible');
update romiku_production_orders set status='in_production' where id=(select p from cases where label='late_status');
insert into romiku_production_followups(production_order_id,method,summary) select p,'email','late followup' from cases where label='late_followup';
update romiku_production_orders set archived_at=now() where id=(select p from cases where label='late_archive');
insert into romiku_packing_lists(order_id) select id from cases where label='late_pack';
create temporary table late_results as select romiku_batch_delete_orders(array(select id from cases where label like 'late_%' or label in ('rollback','batch_survivor'))) value;
select is(jsonb_array_length(value->'deleted'),1,'one failure does not roll back another Order success') from late_results;
select is(jsonb_array_length(value->'failed'),5,'four new dependencies and one rollback reported') from late_results;
select is((select count(*) from late_results,jsonb_array_elements(value->'failed') f where f->>'status'='blocked_at_execution'),4::bigint,'status followup archive packing rechecked at execution');
select is((select count(*) from romiku_production_orders where order_id=(select id from cases where label='rollback')),2::bigint,'batch rollback preserves earlier child deletes');
-- Upstream records and both number ledgers remain, including barcode reservations.
insert into cases(label) values ('sources');
create temporary table source_ids(kind text primary key,id uuid default gen_random_uuid());
insert into source_ids(kind) values ('quote'),('pi'),('customer'),('outbound'),('inquiry');
insert into romiku_outbound_companies(id,name) select id,'Cascade keep outbound' from source_ids where kind='outbound';
insert into romiku_formal_customers(id,name) select id,'Cascade keep buyer' from source_ids where kind='customer';
insert into romiku_website_inquiries(id,customer_name,email) select id,'Cascade keep inquiry','cascade@test.example' from source_ids where kind='inquiry';
insert into romiku_quotes(id) select id from source_ids where kind='quote';
insert into romiku_pis(id,source_quote_id) select id,(select id from source_ids where kind='quote') from source_ids where kind='pi';
insert into romiku_orders(id,source_quote_id,source_pi_id,formal_customer_id,outbound_company_id,source_website_inquiry_id) select id,(select id from source_ids where kind='quote'),(select id from source_ids where kind='pi'),(select id from source_ids where kind='customer'),(select id from source_ids where kind='outbound'),(select id from source_ids where kind='inquiry') from cases where label='sources';
insert into romiku_order_items(id,order_id,sku,quantity) select item,id,'COUNTER-KEEP',10 from cases where label='sources';
insert into romiku_production_orders(id,order_id) select p,id from cases where label='sources';
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity,barcode_number) select p,id,item,'COUNTER-KEEP',1,'0123456789012' from cases where label='sources';
reset role;
create temporary table saved_counter as select * from romiku_document_daily_counters;
set local role authenticated;
select is(romiku_delete_record('order',(select id from cases where label='sources')),'{"ok":true}'::jsonb,'safe cascade with upstream chain succeeds');
select ok(exists(select 1 from romiku_quotes where id=(select id from source_ids where kind='quote')),'Quote retained');
select ok(exists(select 1 from romiku_pis where id=(select id from source_ids where kind='pi')),'PI retained');
select ok(exists(select 1 from romiku_formal_customers where id=(select id from source_ids where kind='customer')),'Customer retained');
select ok(exists(select 1 from romiku_website_inquiries where id=(select id from source_ids where kind='inquiry')),'Inquiry retained');
select ok(exists(select 1 from romiku_outbound_companies where id=(select id from source_ids where kind='outbound')),'Outbound retained');
select ok(exists(select 1 from romiku_production_barcodes where barcode_number='0123456789012' and source_order_item_id is null),'barcode reservation retained and source detached');
reset role;
select results_eq('select * from romiku_document_daily_counters order by 1,2,3','select * from saved_counter order by 1,2,3','global document numbering counters unchanged');
select * from finish();
rollback;
