begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email) values('de610000-0000-0000-0000-000000000001','workflow@test.example');
select ok(not has_table_privilege('authenticated','romiku_payments','delete'),'no authenticated Payment DELETE');
select ok(not has_function_privilege('anon','romiku_void_payment(uuid,text)','execute'),'anon void denied');
select ok(not has_function_privilege('anon','romiku_batch_status(text,uuid[],text)','execute'),'anon bulk status denied');
select ok(not has_function_privilege('anon','romiku_delete_preflight(text,uuid[])','execute'),'anon preflight denied');
set local role authenticated;
select is(romiku_void_payment(gen_random_uuid(),'reason')->>'code','UNAUTHENTICATED','void requires uid');
select is(romiku_batch_status('quote',array[gen_random_uuid()],'won')->>'code','UNAUTHENTICATED','batch requires uid');
select set_config('request.jwt.claim.sub','de610000-0000-0000-0000-000000000001',true);
create temporary table ids(kind text primary key,id uuid default gen_random_uuid(),child uuid default gen_random_uuid());
insert into ids(kind) values('order'),('quote'),('pi'),('production'),('packing'),('website_inquiry'),('outbound'),('customer'),('payment'),('payment2'),('production2'),('order2');
insert into romiku_formal_customers(id,name) select id,'Workflow Customer' from ids where kind='customer';
insert into romiku_orders(id,formal_customer_id,freight,currency) select id,(select id from ids where kind='customer'),10000,'USD' from ids where kind='order';
insert into romiku_orders(id) select id from ids where kind='order2';
insert into romiku_quotes(id) select id from ids where kind='quote';
insert into romiku_pis(id) select id from ids where kind='pi';
insert into romiku_packing_lists(id) select id from ids where kind='packing';
insert into romiku_outbound_companies(id,name) select id,'Workflow Outbound' from ids where kind='outbound';
insert into romiku_website_inquiries(id,customer_name,email) select id,'Workflow Inquiry','workflow@example.test' from ids where kind='website_inquiry';
select is((select status from romiku_quotes where id=(select id from ids where kind='quote')),'pending_quote','new quote default');
select is((select status from romiku_packing_lists where id=(select id from ids where kind='packing')),'draft','new packing default');
select is((select status from romiku_website_inquiries where id=(select id from ids where kind='website_inquiry')),'pending_screening','new inquiry default');
insert into romiku_order_items(id,order_id,sku,quantity) select child,id,'WORKFLOW',10 from ids where kind='order';
insert into romiku_production_orders(id,order_id) select id,(select id from ids where kind='order') from ids where kind in ('production','production2');
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity) select (select id from ids where kind='production'),id,child,'WORKFLOW',10 from ids where kind='order';
select is((select status from romiku_production_orders where id=(select id from ids where kind='production')),'pending_send','production default');
select is(romiku_batch_status('quote',array[(select id from ids where kind='quote')],'quoted')->>'ok','true','quote sent');
select is(romiku_batch_status('quote',array[(select id from ids where kind='quote')],'won')->>'ok','true','quote won');
select is(romiku_batch_status('pi',array[(select id from ids where kind='pi')],'confirmed')->>'ok','true','PI confirmed');
select is(romiku_batch_status('packing',array[(select id from ids where kind='packing')],'incomplete')->>'ok','true','packing incomplete');
select is(romiku_batch_status('packing',array[(select id from ids where kind='packing')],'completed')->>'ok','true','packing completed');
select is(romiku_batch_status('packing',array[(select id from ids where kind='packing')],'sent')->>'ok','true','packing sent');
select is(romiku_batch_status('website_inquiry',array[(select id from ids where kind='website_inquiry')],value)->>'ok','true','inquiry status '||value) from unnest(array['pending_contact','pending_quote','quoted','following_up','customer_no_reply','won','invalid','pending_screening']) value;
select is(romiku_batch_status('order',array[(select id from ids where kind='order')],'voided')->>'code','UNSUPPORTED_KIND','Order not arbitrary batch status');
select is(romiku_batch_status('quote',array[(select id from ids where kind='quote')],'confirmed')->>'code','INVALID_STATUS','fixed status whitelist');
select is(romiku_batch_status('quote',array[(select id from ids where kind='pi')],'quoted')->'failed'->0->>'code','NOT_FOUND','wrong resource ID rejected');
select is(romiku_batch_status('production',array[(select id from ids where kind='production')],'scheduled')->>'ok','true','production scheduled');
select is(romiku_batch_status('production',array[(select id from ids where kind='production')],'received')->>'ok','true','production received');
select is((select unallocated_quantity from romiku_order_item_remaining where id=(select child from ids where kind='order')),0::numeric,'received still occupies');
update romiku_production_orders set archived_at=now() where id=(select id from ids where kind='production');
select is((select unallocated_quantity from romiku_order_item_remaining where id=(select child from ids where kind='order')),0::numeric,'archive still occupies');
select is(romiku_batch_status('production',array[(select id from ids where kind='production')],'cancelled')->>'ok','true','cancel frees');
select is((select unallocated_quantity from romiku_order_item_remaining where id=(select child from ids where kind='order')),10::numeric,'cancelled quantity released');
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity) select (select id from ids where kind='production2'),id,child,'WORKFLOW',10 from ids where kind='order';
select is(romiku_batch_status('production',array[(select id from ids where kind='production'),(select id from ids where kind='production2')],'scheduled')->'failed'->0->>'code','OVER_ALLOCATED','restoration over capacity blocked per-record');
select is((select status from romiku_production_orders where id=(select id from ids where kind='production')),'cancelled','failed restore rolled back');
insert into romiku_payments(id,order_id,kind,amount) select id,(select id from ids where kind='order'),'deposit',3000 from ids where kind='payment';
select is((select received_amount from romiku_order_totals where id=(select id from ids where kind='order')),3000::numeric,'Paid 3000');
select is((select remaining_amount from romiku_order_totals where id=(select id from ids where kind='order')),7000::numeric,'Balance 7000');
select is(romiku_void_payment((select id from ids where kind='payment'),' ')->>'code','INVALID_REASON','reason required');
select throws_ok($$delete from romiku_payments where id=(select id from ids where kind='payment')$$,'42501',null,'direct payment deletion forbidden');
select throws_ok($$update romiku_payments set order_id=(select id from ids where kind='order2') where id=(select id from ids where kind='payment')$$,'P4202',null,'reparent history forbidden');
select throws_ok($$update romiku_payments set status='voided',voided_at=now(),voided_by=auth.uid(),voided_by_label='fake',void_reason='fake' where id=(select id from ids where kind='payment')$$,'P4202',null,'direct spoofed void forbidden');
select is(romiku_delete_record('order',(select id from ids where kind='order'))->>'message','该订单存在收款历史，不能永久删除。可以作废订单。','active history blocks with correct reason');
select is(romiku_void_payment((select id from ids where kind='payment'),'重复录入')->>'ok','true','controlled void succeeds');
select ok((select status='voided' and voided_at is not null and voided_by=auth.uid() and voided_by_label='workflow@test.example' and void_reason='重复录入' and amount=3000 from romiku_payments where id=(select id from ids where kind='payment')),'audit and original money preserved');
select is((select received_amount from romiku_order_totals where id=(select id from ids where kind='order')),0::numeric,'void paid zero');
select is((select remaining_amount from romiku_order_totals where id=(select id from ids where kind='order')),10000::numeric,'void balance 10000');
select is(romiku_customer_business_history((select id from ids where kind='customer'))->'orders'->0->'payment_summary'->>'paid','0','Customer360 active totals');
select is(romiku_customer_business_history((select id from ids where kind='customer'))->'orders'->0->'payments'->0->>'status','voided','Customer360 retains void history');
select throws_ok($$update romiku_payments set status='active' where id=(select id from ids where kind='payment')$$,'P4202',null,'void cannot restore');
select throws_ok($$update romiku_payments set amount=10 where id=(select id from ids where kind='payment')$$,'P4202',null,'void original money immutable');
select is(romiku_delete_record('order',(select id from ids where kind='order'))->>'message','该订单存在收款历史，不能永久删除。可以作废订单。','void history still blocks');
insert into romiku_payments(id,order_id,kind,amount) select id,(select id from ids where kind='order'),'deposit',3000 from ids where kind='payment2';
select is((select received_amount from romiku_order_totals where id=(select id from ids where kind='order')),3000::numeric,'correct re-entry 3000');
select is((select remaining_amount from romiku_order_totals where id=(select id from ids where kind='order')),7000::numeric,'correct re-entry balance 7000');
select throws_ok($$update romiku_orders set status='voided' where id=(select id from ids where kind='order')$$,'P4202',null,'direct Order void denied');
select is(romiku_void_order((select id from ids where kind='order'),'取消交易')->>'ok','true','Order void allowed with histories');
select is((select count(*) from romiku_payments where order_id=(select id from ids where kind='order')),2::bigint,'Order void retains both payments');
select is((select count(*) from romiku_production_orders where order_id=(select id from ids where kind='order')),2::bigint,'Order void retains productions');
select throws_ok($$update romiku_orders set status='draft' where id=(select id from ids where kind='order')$$,'P4202',null,'no ordinary Order restoration');
select is(romiku_archive_orders(array[(select id from ids where kind='order')])->>'ok','true','archive independent');
select is((select status from romiku_orders where id=(select id from ids where kind='order')),'voided','archive keeps status');
select is(romiku_customer_business_history((select id from ids where kind='customer'))->>'total_count','1','archived voided retained in Customer360');
-- Mixed quote preflight + execution recheck; source remains.
update romiku_pis set source_quote_id=(select id from ids where kind='quote') where id=(select id from ids where kind='pi');
select is(jsonb_array_length(romiku_delete_preflight('quote',array[(select id from ids where kind='quote')])->'blocked'),1,'quote downstream blocked');
select is(jsonb_array_length(romiku_delete_preflight('pi',array[(select id from ids where kind='pi')])->'deletable'),1,'PI without order eligible');
update romiku_orders set source_pi_id=(select id from ids where kind='pi') where id=(select id from ids where kind='order2');
select is(romiku_batch_delete('pi',array[(select id from ids where kind='pi')])->'failed'->0->>'status','blocked_at_execution','PI execution rechecks');
insert into romiku_production_followups(production_order_id,method,summary) select id,'email','history' from ids where kind='production';
select is(jsonb_array_length(romiku_delete_preflight('production',array[(select id from ids where kind='production'),(select id from ids where kind='production2')])->'blocked'),1,'mixed production classified');
select is(jsonb_array_length(romiku_batch_delete('packing',array[(select id from ids where kind='packing')])->'succeeded'),1,'independent packing controlled delete');
update romiku_quotes set source_website_inquiry_id=(select id from ids where kind='website_inquiry') where id=(select id from ids where kind='quote');
select is(jsonb_array_length(romiku_delete_preflight('website_inquiry',array[(select id from ids where kind='website_inquiry')])->'blocked'),1,'Inquiry commercial source blocked');
select is(romiku_delete_record('website_inquiry',(select id from ids where kind='website_inquiry'))->>'code','HAS_DOWNSTREAM','Inquiry actual delete blocked');
update romiku_quotes set outbound_company_id=(select id from ids where kind='outbound') where id=(select id from ids where kind='quote');
select is(jsonb_array_length(romiku_batch_delete('outbound',array[(select id from ids where kind='outbound')])->'succeeded'),1,'Outbound commercial detach allowed');
select ok(exists(select 1 from romiku_quotes where id=(select id from ids where kind='quote') and outbound_company_id is null),'Quote survives Outbound deletion');
-- A free inquiry must pass both preflight and the immutable-originals trigger.
insert into ids(kind) values('free_inquiry');
insert into romiku_website_inquiries(id,customer_name,email) select id,'Free QA Inquiry','free@example.test' from ids where kind='free_inquiry';
insert into romiku_website_inquiry_items(inquiry_id,sku,quantity) select id,'FREE',1 from ids where kind='free_inquiry';
insert into romiku_website_inquiry_followups(inquiry_id,method,summary) select id,'email','Own followup' from ids where kind='free_inquiry';
select is(jsonb_array_length(romiku_delete_preflight('website_inquiry',array[(select id from ids where kind='free_inquiry')])->'deletable'),1,'free Inquiry preflight eligible');
select throws_ok($$update romiku_website_inquiries set message='changed' where id=(select id from ids where kind='free_inquiry')$$,'23514',null,'Inquiry originals remain immutable');
select set_config('romiku.controlled_inquiry_delete',(select id::text from ids where kind='free_inquiry'),true);
select throws_ok($$delete from romiku_website_inquiries where id=(select id from ids where kind='free_inquiry')$$,'42501',null,'spoofed controlled-delete marker cannot bypass permissions');
select set_config('romiku.controlled_inquiry_delete','',true);

select is(romiku_delete_record('website_inquiry',(select id from ids where kind='free_inquiry'))->>'ok','true','free Inquiry controlled deletion passes originals guard');
select is(current_setting('romiku.controlled_inquiry_delete',true),'','controlled Inquiry deletion clears its permit');
select is((select count(*) from romiku_website_inquiry_items where inquiry_id=(select id from ids where kind='free_inquiry')),0::bigint,'free Inquiry items deleted');
select is((select count(*) from romiku_website_inquiry_followups where inquiry_id=(select id from ids where kind='free_inquiry')),0::bigint,'free Inquiry followups deleted');
select throws_ok($$delete from romiku_website_inquiries where false$$,'42501',null,'direct Inquiry header delete still denied');
select throws_ok($$delete from romiku_website_inquiry_items where false$$,'42501',null,'direct Inquiry item delete still denied');
select * from finish();
rollback;
