begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values ('de300000-0000-0000-0000-000000000001','production-delete-test@example.test','{}');
select ok(not has_function_privilege('anon','public.romiku_delete_record(text,uuid)','execute'),'anon cannot call production delete RPC');
set local role authenticated;
select is(romiku_delete_record('production',gen_random_uuid())->>'code','UNAUTHENTICATED','production delete requires user');
select set_config('request.jwt.claim.sub','de300000-0000-0000-0000-000000000001',true);
select is(romiku_delete_record('production',gen_random_uuid())->>'code','NOT_FOUND','production kind is supported and missing record is safe');
select throws_ok($$delete from romiku_production_orders where false$$,'42501',null,'authenticated cannot directly delete production header');
create temporary table production_delete_ids(kind text primary key,id uuid default gen_random_uuid());
insert into production_delete_ids(kind) values ('order'),('item'),('production'),('task');
insert into romiku_orders(id,counterparty_snapshot,notes) select id,'{"name":"Historical Buyer","whatsapp":"+593 99 123-4567"}','Keep commercial notes' from production_delete_ids where kind='order';
insert into romiku_order_items(id,order_id,sku,quantity,product_snapshot) values ((select id from production_delete_ids where kind='item'),(select id from production_delete_ids where kind='order'),'KEEP-SKU',10,'{"name":"Saved source product"}');
insert into romiku_production_orders(id,order_id) values ((select id from production_delete_ids where kind='production'),(select id from production_delete_ids where kind='order'));
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity) values ((select id from production_delete_ids where kind='production'),(select id from production_delete_ids where kind='order'),(select id from production_delete_ids where kind='item'),'KEEP-SKU',4);
insert into romiku_manual_tasks(id,title,notes,production_order_id) values ((select id from production_delete_ids where kind='task'),'Keep production task','Keep manual content',(select id from production_delete_ids where kind='production'));
insert into romiku_production_followups(production_order_id,method,summary) select id,'email','Saved factory history' from production_delete_ids cross join generate_series(1,2) where kind='production';
select is(romiku_delete_record('production',(select id from production_delete_ids where kind='production'))->>'code','HAS_DOWNSTREAM','followups block production deletion');
select is(romiku_delete_record('production',(select id from production_delete_ids where kind='production'))->'dependencies','{"production_followups":2}'::jsonb,'followups count returned structurally');
select is(romiku_delete_record('production',(select id from production_delete_ids where kind='production'))->>'message','该生产单已有 2 条生产跟进记录，无法删除。','followup count readable to user');
select is((select count(*) from romiku_production_items where production_order_id=(select id from production_delete_ids where kind='production')),1::bigint,'blocked delete retains production items');
select ok(exists(select 1 from romiku_manual_tasks where id=(select id from production_delete_ids where kind='task') and production_order_id=(select id from production_delete_ids where kind='production')),'blocked delete retains manual association');
select is((select unallocated_quantity from romiku_order_item_remaining where id=(select id from production_delete_ids where kind='item')),6::numeric,'fixture allocates production quantity');
reset role;
delete from romiku_production_followups where production_order_id=(select id from production_delete_ids where kind='production');
create function public.production_delete_test_fail() returns trigger language plpgsql as $$ begin raise exception 'private production foreign key details'; end $$;
create trigger production_delete_test_fail before delete on romiku_production_orders for each row execute function public.production_delete_test_fail();
set local role authenticated;
select is(romiku_delete_record('production',(select id from production_delete_ids where kind='production'))->>'code','DELETE_FAILED','late failure returns structured failure');
select ok(position('private production' in (romiku_delete_record('production',(select id from production_delete_ids where kind='production'))->>'message'))=0,'raw PostgreSQL details not exposed');
select is((select count(*) from romiku_production_items where production_order_id=(select id from production_delete_ids where kind='production')),1::bigint,'late failure restores deleted items');
select ok(exists(select 1 from romiku_manual_tasks where id=(select id from production_delete_ids where kind='task') and production_order_id=(select id from production_delete_ids where kind='production')),'late failure restores manual link');
reset role;
drop trigger production_delete_test_fail on romiku_production_orders;
set local role authenticated;
select is(romiku_delete_record('production',(select id from production_delete_ids where kind='production')),'{"ok":true}'::jsonb,'production with no followups is deleted');
select is((select count(*) from romiku_production_orders where id=(select id from production_delete_ids where kind='production')),0::bigint,'header removed');
select is((select count(*) from romiku_production_items where production_order_id=(select id from production_delete_ids where kind='production')),0::bigint,'own items removed');
select ok(exists(select 1 from romiku_manual_tasks where id=(select id from production_delete_ids where kind='task') and production_order_id is null and title='Keep production task' and notes='Keep manual content'),'manual task detached and content preserved');
select ok(exists(select 1 from romiku_orders where id=(select id from production_delete_ids where kind='order') and counterparty_snapshot='{"name":"Historical Buyer","whatsapp":"+593 99 123-4567"}'::jsonb and notes='Keep commercial notes'),'Order snapshot and notes unchanged');
select ok(exists(select 1 from romiku_order_items where id=(select id from production_delete_ids where kind='item') and sku='KEEP-SKU' and quantity=10 and product_snapshot='{"name":"Saved source product"}'::jsonb),'source Order item unchanged');
select is((select unallocated_quantity from romiku_order_item_remaining where id=(select id from production_delete_ids where kind='item')),10::numeric,'unallocated quantity naturally restores');
reset role;
select is((select last_value from romiku_production_order_counters where order_id=(select id from production_delete_ids where kind='order')),1,'production numbering counter retained');
set local role authenticated;
insert into romiku_production_orders(order_id) select id from production_delete_ids where kind='order';
select ok(exists(select 1 from romiku_production_orders where order_id=(select id from production_delete_ids where kind='order') and document_number like '%-P02'),'deleted production number is never recycled');
select * from finish();
rollback;
