begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_function('public','romiku_save_production_workspace',array['uuid','uuid','jsonb','jsonb','jsonb'],'atomic Production workspace RPC exists');
select has_function('public','romiku_sync_order_production_defaults',array['uuid','jsonb'],'explicit Order sync RPC exists');


insert into auth.users(id,email,raw_user_meta_data) values('de600000-0000-0000-0000-000000000001','workspace@example.test','{}');
create temporary table ws_ids(kind text primary key,id uuid default gen_random_uuid());
insert into ws_ids(kind) values('order'),('other'),('source'),('foreign');
grant all on ws_ids to authenticated;
create temporary table ws_result(value jsonb); grant all on ws_result to authenticated;
create function pg_temp.ws_expected(pid uuid) returns jsonb language sql as $$select jsonb_build_object('header_updated_at',p.updated_at,'items',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'updated_at',i.updated_at)),'[]') from romiku_production_items i where i.production_order_id=p.id)) from romiku_production_orders p where p.id=pid$$;
create function pg_temp.ws_items(pid uuid) returns jsonb language sql as $$select jsonb_agg(jsonb_build_object('id',i.id,'source_order_item_id',i.source_order_item_id,'quantity',i.quantity,'product_snapshot',jsonb_build_object('specification',i.product_snapshot->>'specification'),'packaging_snapshot','{}'::jsonb,'marking_override',i.marking_override)) from romiku_production_items i where i.production_order_id=pid$$;
set local role authenticated;
select set_config('request.jwt.claim.sub','de600000-0000-0000-0000-000000000001',true);
insert into romiku_orders(id,notes) select id,'Original saved Order' from ws_ids where kind in ('order','other');
insert into romiku_order_items(id,order_id,sku,quantity,product_snapshot,packing_snapshot) select i.id,o.id,'SUN5',100,'{"name":"Saved lamp","unit":"PCS","specification":"Original"}','{"cartons":2,"material":"Paper"}' from ws_ids i cross join ws_ids o where i.kind='source' and o.kind='order';
insert into romiku_order_items(id,order_id,sku,quantity) select i.id,o.id,'OTHER',100 from ws_ids i cross join ws_ids o where i.kind='foreign' and o.kind='other';
insert into ws_result select romiku_save_production_workspace(null,o.id,'{}',jsonb_build_array(jsonb_build_object('source_order_item_id',s.id,'quantity',30,'product_snapshot','{}'::jsonb,'packaging_snapshot','{}'::jsonb)),jsonb_build_object('order_updated_at',o.updated_at)) from romiku_orders o cross join ws_ids s where o.id=(select id from ws_ids where kind='order') and s.kind='source';
select is((select value->>'ok' from ws_result),'true','atomic create succeeds');
insert into ws_ids select 'production',(value->>'id')::uuid from ws_result;

select is((select barcode_number from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),null::text,'create does not generate');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}',jsonb_set(pg_temp.ws_items(p.id),'{0,barcode_number}','" 0123456789012 "'),pg_temp.ws_expected(p.id))->>'ok','true','valid barcode saves transactionally') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select barcode_number from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'0123456789012','TEXT trim and leading zero');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"must rollback"}',jsonb_set(pg_temp.ws_items(p.id),'{0,barcode_number}','"1234567890129"'),pg_temp.ws_expected(p.id))->>'code','INVALID_BARCODE','invalid check digit rejects') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select isnt((select notes from romiku_production_orders where id=(select id from ws_ids where kind='production')),'must rollback','invalid barcode rolls back header');
select is((select barcode_number from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'0123456789012','invalid barcode leaves saved value');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}',pg_temp.ws_items(p.id),pg_temp.ws_expected(p.id))->>'ok','true','old client missing barcode remains compatible') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select barcode_number from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'0123456789012','omitted barcode does not erase');
select is(romiku_production_barcode((select id from ws_ids where kind='source'),true)->>'kind','reuse','split Production offers saved reuse, no new number');
select is(romiku_production_barcode((select id from ws_ids where kind='source'),true)#>>'{candidates,0}','0123456789012','reuse correct saved string');
truncate ws_result;insert into ws_result select romiku_production_barcode((select id from ws_ids where kind='foreign'),true);
select is((select value->>'kind' from ws_result),'generated','explicit generation produces preview');
select ok(public.romiku_valid_ean13((select value#>>'{candidates,0}' from ws_result)),'generated check digit valid');
select is(romiku_production_barcode((select id from ws_ids where kind='foreign'),true)#>>'{candidates,0}',(select value#>>'{candidates,0}' from ws_result),'consecutive generation reuses reservation');
select throws_ok($$insert into romiku_production_barcodes(barcode_number,sku,source) values('0123456789012','OTHER','manual')$$,'23505',null,'registry unique number prevents race collision');
select lives_ok($$update romiku_production_items set barcode_number='0123456789012' where production_order_id=(select id from ws_ids where kind='production')$$,'same product allowed same code');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}',jsonb_set(pg_temp.ws_items(p.id),'{0,barcode_number}','" "'),pg_temp.ws_expected(p.id))->>'ok','true','explicit clear saves') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select barcode_number from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),null::text,'empty stored as null');
update romiku_order_items set sku='RENAMED SUN5' where id=(select id from ws_ids where kind='source');
truncate ws_result;insert into ws_result select romiku_production_barcode(i.source_order_item_id,true,i.id) from romiku_production_items i where production_order_id=(select id from ws_ids where kind='production');
select is((select value#>>'{candidates,0}' from ws_result),'0123456789012','renamed live Order SKU still proposes saved Production identity');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}',jsonb_set(pg_temp.ws_items(p.id),'{0,barcode_number}',(select value#>'{candidates,0}' from ws_result)),pg_temp.ws_expected(p.id))->>'ok','true','saved Production SKU can still save generated or reused code after Order rename') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select sku from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'SUN5','barcode does not mutate historical SKU');
select is(romiku_production_barcode((select id from ws_ids where kind='foreign'),true,(select id from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')))->>'ok','false','cannot mix Production item and another Order source');
select set_config('request.jwt.claim.sub','',true);
select is(romiku_production_barcode((select id from ws_ids where kind='source'),true)->>'ok','false','no uid cannot generate');
reset role;
select ok(not has_function_privilege('anon','public.romiku_production_barcode(uuid,boolean,uuid)','execute'),'anon no barcode RPC');
select ok(not has_table_privilege('anon','public.romiku_production_barcodes','select'),'anon no registry');
select ok(not has_table_privilege('authenticated','public.romiku_production_barcodes','update'),'reservations immutable');
select is((select prosecdef from pg_proc where oid='public.romiku_production_barcode(uuid,boolean,uuid)'::regprocedure),false,'generator respects RLS');
select set_config('request.jwt.claim.sub','de600000-0000-0000-0000-000000000001',true);
create policy barcode_deny_read on romiku_order_items as restrictive for select to authenticated using(false);
set local role authenticated;
select is(romiku_production_barcode((select id from ws_ids where kind='source'),true)->>'ok','false','source RLS enforced');
reset role;drop policy barcode_deny_read on romiku_order_items;
select * from finish();rollback;
