begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_function('public','romiku_save_production_workspace',array['uuid','uuid','jsonb','jsonb','jsonb'],'atomic Production workspace RPC exists');
select has_function('public','romiku_sync_order_production_defaults',array['uuid','jsonb'],'explicit Order sync RPC exists');


insert into auth.users(id,email,raw_user_meta_data) values('de600000-0000-0000-0000-000000000001','workspace@example.test','{}');
create temporary table ws_ids(kind text primary key,id uuid default gen_random_uuid());
insert into ws_ids(kind) values('order'),('other'),('source'),('foreign');
grant all on ws_ids to authenticated;
create temporary table ws_result(value jsonb); grant all on ws_result to authenticated;
create function pg_temp.ws_expected(pid uuid) returns jsonb language sql as $$select jsonb_build_object('header_updated_at',p.updated_at,'items',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'updated_at',i.updated_at)),'[]') from romiku_production_items i where i.production_order_id=p.id)) from romiku_production_orders p where p.id=pid$$;
create function pg_temp.ws_items(pid uuid) returns jsonb language sql as $$select jsonb_agg(jsonb_build_object('id',i.id,'source_order_item_id',i.source_order_item_id,'quantity',i.quantity,'product_snapshot',jsonb_build_object('specification',i.product_snapshot->>'specification'),'packaging_snapshot','{}'::jsonb,'marking_override',i.marking_override)) from romiku_production_items i where i.production_order_id=pid$$;
set local role authenticated;
select set_config('request.jwt.claim.sub','de600000-0000-0000-0000-000000000001',true);
insert into romiku_orders(id,notes) select id,'Original saved Order' from ws_ids where kind in ('order','other');
insert into romiku_order_items(id,order_id,sku,quantity,product_snapshot,packing_snapshot) select i.id,o.id,'SUN5',100,'{"name":"Saved lamp","unit":"PCS","specification":"Original"}','{"cartons":2,"material":"Paper"}' from ws_ids i cross join ws_ids o where i.kind='source' and o.kind='order';
insert into romiku_order_items(id,order_id,sku,quantity) select i.id,o.id,'OTHER',100 from ws_ids i cross join ws_ids o where i.kind='foreign' and o.kind='other';
insert into ws_result select romiku_save_production_workspace(null,o.id,'{}',jsonb_build_array(jsonb_build_object('source_order_item_id',s.id,'quantity',30,'product_snapshot','{}'::jsonb,'packaging_snapshot','{}'::jsonb)),jsonb_build_object('order_updated_at',o.updated_at)) from romiku_orders o cross join ws_ids s where o.id=(select id from ws_ids where kind='order') and s.kind='source';
select is((select value->>'ok' from ws_result),'true','atomic create succeeds');
insert into ws_ids select 'production',(value->>'id')::uuid from ws_result;
select is((select p.document_number from romiku_production_orders p where id=(select id from ws_ids where kind='production')),(select document_number||'-P01' from romiku_orders where id=(select id from ws_ids where kind='order')),'number uses parent Order counter');
select is((select marking_snapshot->>'production_requirements' from romiku_production_orders where id=(select id from ws_ids where kind='production')),'Original saved Order','copies saved Order instructions');
select is((select product_snapshot->>'unit' from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'PCS','preserves unedited saved item snapshot');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"session saved","marking_snapshot":{"small_label":{"mode":"text","text":"Made in China"}}}',jsonb_set(jsonb_set(pg_temp.ws_items(p.id),'{0,product_snapshot,specification}','"Factory spec"'),'{0,marking_override}','{"mode":"append","labels":[{"mode":"text","text":"Barcode"}]}'),pg_temp.ws_expected(p.id))->>'ok','true','header shared requirements and item override saved together') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select notes from romiku_orders where id=(select id from ws_ids where kind='order')),'Original saved Order','source Order unchanged');
select is((select product_snapshot->>'specification' from romiku_order_items where id=(select id from ws_ids where kind='source')),'Original','source item unchanged');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"stale"}',pg_temp.ws_items(p.id),jsonb_set(pg_temp.ws_expected(p.id),'{header_updated_at}','"2000-01-01"'))->>'code','STALE','stale session rejected') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"bad write"}',jsonb_set(pg_temp.ws_items(p.id),'{0,source_order_item_id}',to_jsonb((select id::text from ws_ids where kind='foreign'))),pg_temp.ws_expected(p.id))->>'ok','false','foreign Order item rejected') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select notes from romiku_production_orders where id=(select id from ws_ids where kind='production')),'session saved','failed line rolls header back');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}',jsonb_set(pg_temp.ws_items(p.id),'{0,quantity}','150'),pg_temp.ws_expected(p.id))->>'code','OVER_ASSIGNED','over assignment is blocked') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select quantity from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),30::numeric,'blocked excess rolls back');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"allow_overassigned":true}',jsonb_set(pg_temp.ws_items(p.id),'{0,quantity}','150'),pg_temp.ws_expected(p.id))->>'ok','false','legacy override cannot bypass capacity') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is(romiku_save_production_workspace(p.id,p.order_id,'{}','[]',pg_temp.ws_expected(p.id))->>'ok','false','empty session cannot erase rows') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"order_id":"invalid"}',pg_temp.ws_items(p.id),pg_temp.ws_expected(p.id))->>'ok','false','header whitelist rejects source mutation') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
insert into romiku_production_orders(order_id,status,marking_snapshot,archived_at) select id,st,'{"production_requirements":"Keep"}',case when st='pending' then now() else null end from ws_ids cross join unnest(array['pending','completed','received','cancelled']) st where kind='order';
truncate ws_result;
insert into ws_result select romiku_sync_order_production_defaults((select id from ws_ids where kind='order'));
select is((select jsonb_array_length(value->'productions') from ws_result),1,'preview excludes archived completed received cancelled');
select is((select marking_snapshot#>>'{small_label,text}' from romiku_production_orders where id=(select id from ws_ids where kind='production')),'Made in China','preview does not write');
update romiku_orders set production_defaults_snapshot=production_defaults_snapshot||'{"production_requirements":"Order new"}' where id=(select id from ws_ids where kind='order');
select is(romiku_sync_order_production_defaults((select id from ws_ids where kind='order'),(select value from ws_result))->>'ok','false','changed Order invalidates preview');
truncate ws_result; insert into ws_result select romiku_sync_order_production_defaults((select id from ws_ids where kind='order'));
select is(romiku_sync_order_production_defaults((select id from ws_ids where kind='order'),(select value from ws_result))->>'ok','true','confirmed sync succeeds');
select is((select marking_snapshot->>'production_requirements' from romiku_production_orders where id=(select id from ws_ids where kind='production')),'Order new','sync copies current saved Order');
select is((select marking_override->>'mode' from romiku_production_items where production_order_id=(select id from ws_ids where kind='production')),'append','sync preserves item overrides');
select is((select count(*) from romiku_production_orders where order_id=(select id from ws_ids where kind='order') and marking_snapshot->>'production_requirements'='Keep'),4::bigint,'excluded Production snapshots unchanged');
select set_config('request.jwt.claim.sub','',true);
select is(romiku_save_production_workspace(null,null,'{}','[]','{}')->>'code','UNAUTHENTICATED','authenticated role without uid blocked');
select is(romiku_sync_order_production_defaults((select id from ws_ids where kind='order'))->>'ok','false','sync requires uid');
reset role;
select ok(not has_function_privilege('anon','public.romiku_save_production_workspace(uuid,uuid,jsonb,jsonb,jsonb)','execute'),'anon cannot save');
select ok(not has_function_privilege('anon','public.romiku_sync_order_production_defaults(uuid,jsonb)','execute'),'anon cannot sync');
select is((select prosecdef from pg_proc where oid='public.romiku_save_production_workspace(uuid,uuid,jsonb,jsonb,jsonb)'::regprocedure),false,'save invoker respects RLS');
select is((select prosecdef from pg_proc where oid='public.romiku_sync_order_production_defaults(uuid,jsonb)'::regprocedure),false,'sync invoker respects RLS');

select set_config('request.jwt.claim.sub','de600000-0000-0000-0000-000000000001',true);
create policy ws_deny_update on romiku_production_items as restrictive for update to authenticated using(false);
set local role authenticated;
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"RLS denied"}',pg_temp.ws_items(p.id),pg_temp.ws_expected(p.id))->>'ok','false','RLS denied row aborts whole session') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select notes from romiku_production_orders where id=(select id from ws_ids where kind='production')),'session saved','RLS failure rolls header back');
reset role; drop policy ws_deny_update on romiku_production_items;
create function pg_temp.ws_fail() returns trigger language plpgsql as $$begin raise exception 'private database trigger detail';end$$;
create trigger ws_late_failure before update on romiku_production_items for each row execute function pg_temp.ws_fail();
set local role authenticated;
select is(romiku_save_production_workspace(p.id,p.order_id,'{"notes":"late failure"}',pg_temp.ws_items(p.id),pg_temp.ws_expected(p.id))->>'message','保存失败，整张生产单未写入，请刷新后重试。','late trigger error is sanitized') from romiku_production_orders p where id=(select id from ws_ids where kind='production');
select is((select notes from romiku_production_orders where id=(select id from ws_ids where kind='production')),'session saved','late trigger rolls header back');
reset role; drop trigger ws_late_failure on romiku_production_items;
create policy ws_deny_order_read on romiku_orders as restrictive for select to authenticated using(false);
set local role authenticated;
select is(romiku_sync_order_production_defaults((select id from ws_ids where kind='order'))->>'ok','false','sync respects source Order RLS');
reset role; drop policy ws_deny_order_read on romiku_orders;
set local role authenticated;
select is(romiku_save_production_workspace(null,o.id,'{}',jsonb_build_array(jsonb_build_object('source_order_item_id',(select id from ws_ids where kind='foreign'),'quantity',10,'product_snapshot','{}'::jsonb,'packaging_snapshot','{}'::jsonb)),jsonb_build_object('order_updated_at',o.updated_at))->>'ok','false','invalid create rolls back new header') from romiku_orders o where id=(select id from ws_ids where kind='order');
select is((select count(*) from romiku_production_orders where order_id=(select id from ws_ids where kind='order')),5::bigint,'no partial new Production remains');
reset role;
select is((select last_value from romiku_production_order_counters where order_id=(select id from ws_ids where kind='order')),5,'failed create does not consume Pxx');
reset role;
select * from finish();
rollback;
