begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_table('public','romiku_status_history','unified history exists');
select has_column('public','romiku_quotes','status_changed_at','status timestamp exists');
insert into auth.users(id,email) values('de630000-0000-0000-0000-000000000001','status-history@test.example');
set local role authenticated;
select set_config('request.jwt.claim.sub','de630000-0000-0000-0000-000000000001',true);
create temporary table sh_ids as select gen_random_uuid() q,gen_random_uuid() i,gen_random_uuid() o,gen_random_uuid() p,gen_random_uuid() pl,gen_random_uuid() pi,gen_random_uuid() out;
insert into romiku_quotes(id,notes) select q,'Status history fixture' from sh_ids;
insert into romiku_website_inquiries(id,customer_name,message) select i,'History fixture','Keep original' from sh_ids;
insert into romiku_pis(id) select pi from sh_ids;
insert into romiku_orders(id) select o from sh_ids;
insert into romiku_production_orders(id,order_id) select p,o from sh_ids;
insert into romiku_packing_lists(id) select pl from sh_ids;
insert into romiku_outbound_companies(id,name) select out,'History outbound' from sh_ids;
select is((select count(*) from romiku_status_history where resource_id in(select q from sh_ids union select i from sh_ids union select pi from sh_ids union select o from sh_ids union select p from sh_ids union select pl from sh_ids union select out from sh_ids)),7::bigint,'each resource gets initial history');
select is((select change_source from romiku_status_history where resource_id=(select q from sh_ids)),'create','initial source create');
select is((select from_status from romiku_status_history where resource_id=(select q from sh_ids)),null::text,'initial from is null');
select is((select changed_by from romiku_status_history where resource_id=(select q from sh_ids)),auth.uid(),'initial actor from auth');
create temporary table sh_before as select status_changed_at from romiku_quotes where id=(select q from sh_ids);
update romiku_quotes set notes='unrelated',status_changed_at='2000-01-01' where id=(select q from sh_ids);
update romiku_quotes set status='pending_quote' where id=(select q from sh_ids);
select is((select status_changed_at from romiku_quotes where id=(select q from sh_ids)),(select status_changed_at from sh_before),'unrelated edit, forgery and same-status do not reset timestamp');
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),1::bigint,'same status and notes do not add history');
select set_config('romiku.status_change_source','batch',true);
select set_config('romiku.status_batch_at','2000-01-01T00:00:00Z',true);
update romiku_quotes set status='sent' where id=(select q from sh_ids);
select ok((select status_changed_at from romiku_quotes where id=(select q from sh_ids))>(select status_changed_at from sh_before),'batch start before a newer row must not move timestamp backwards');
select set_config('romiku.status_change_source','',true);
select is((select to_status from romiku_status_history where resource_id=(select q from sh_ids) order by changed_at desc,id desc limit 1),'quoted','history captures normalized final value');
select is((select from_status from romiku_status_history where resource_id=(select q from sh_ids) order by changed_at desc,id desc limit 1),'pending_quote','from_status correct');
select is((select change_source from romiku_status_history where resource_id=(select q from sh_ids) order by changed_at desc,id desc limit 1),'batch','batch source context');
select ok((select status_changed_at from romiku_quotes where id=(select q from sh_ids))>(select status_changed_at from sh_before),'actual change advances timestamp');
select is((select status_changed_at from romiku_quotes where id=(select q from sh_ids)),(select max(changed_at) from romiku_status_history where resource_id=(select q from sh_ids)),'history and current timestamp identical');
update romiku_quotes set status='following_up' where id=(select q from sh_ids);
update romiku_quotes set status='customer_no_reply' where id=(select q from sh_ids);
update romiku_quotes set status='following_up' where id=(select q from sh_ids);
update romiku_quotes set status='won' where id=(select q from sh_ids);
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),6::bigint,'Quote retains create plus five transitions');
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids) and to_status='following_up'),2::bigint,'repeat state does not overwrite');
select is(romiku_batch_status('website_inquiry',array[(select i from sh_ids),gen_random_uuid()],'pending_contact')->'succeeded'->0->>'id',(select i::text from sh_ids),'bulk successful row');
select is((select change_source from romiku_status_history where resource_id=(select i from sh_ids) order by changed_at desc,id desc limit 1),'batch','bulk source recorded');
select is((select changed_by from romiku_status_history where resource_id=(select i from sh_ids) order by changed_at desc,id desc limit 1),auth.uid(),'bulk actor');
select is((select count(*) from romiku_status_history where resource_id=(select i from sh_ids)),2::bigint,'failed bulk id creates no extra history');
select romiku_batch_status('website_inquiry',array[(select i from sh_ids)],'pending_contact');
select is((select count(*) from romiku_status_history where resource_id=(select i from sh_ids)),2::bigint,'batch same-state no-op');
update romiku_website_inquiries set status='pending_quote' where id=(select i from sh_ids);
select is((select change_source from romiku_status_history where resource_id=(select i from sh_ids) order by changed_at desc,id desc limit 1),'manual','batch context restored');
select throws_ok($$update romiku_quotes set status='bad' where id=(select q from sh_ids)$$,'23514',null,'invalid status fails');
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),6::bigint,'failed status creates no history');
select throws_ok($$insert into romiku_status_history(resource_type,resource_id,to_status) select 'quote',q,'won' from sh_ids$$,'42501',null,'authenticated cannot insert history');
select throws_ok($$update romiku_status_history set changed_by=null$$,'42501',null,'authenticated cannot update audit');
select throws_ok($$delete from romiku_status_history$$,'42501',null,'authenticated cannot delete audit');
-- Financial audit keeps its own lifecycle; only Order business void joins this ledger.
create temporary table sh_fin as select gen_random_uuid() o,gen_random_uuid() pay;
insert into romiku_orders(id) select o from sh_fin;
insert into romiku_payments(id,order_id,amount,kind) select pay,o,5,'deposit' from sh_fin;
select is(romiku_void_payment((select pay from sh_fin),'status audit regression')->>'ok','true','Payment void still succeeds');
select is((select count(*) from romiku_status_history where resource_id=(select pay from sh_fin)),0::bigint,'Payment remains outside status ledger');
select ok((select voided_at is not null and voided_by=auth.uid() and void_reason='status audit regression' from romiku_payments where id=(select pay from sh_fin)),'Payment financial attribution preserved');
select is(romiku_void_order((select o from sh_fin),'status audit regression')->>'ok','true','controlled Order void succeeds');
select is((select to_status from romiku_status_history where resource_id=(select o from sh_fin) order by changed_at desc,id desc limit 1),'voided','Order void recorded in business history');
select is((select count(*) from romiku_status_history where resource_id=(select o from sh_fin)),2::bigint,'Order create and controlled void each logged once');
-- Every resource uses the same actual-transition writer.
update romiku_pis set status='sent' where id=(select pi from sh_ids);
update romiku_outbound_companies set status='contacted' where id=(select out from sh_ids);
update romiku_production_orders set status='scheduled' where id=(select p from sh_ids);
update romiku_production_orders set status='received' where id=(select p from sh_ids);
select is((select array_agg(to_status order by changed_at,id) from romiku_status_history where resource_id=(select p from sh_ids)),array['pending_send','scheduled','received'],'Production stages retained');
update romiku_production_orders set status='pending_send' where id=(select p from sh_ids);
update romiku_packing_lists set status='incomplete' where id=(select pl from sh_ids);
update romiku_packing_lists set status='draft' where id=(select pl from sh_ids);
update romiku_packing_lists set status='completed' where id=(select pl from sh_ids);
update romiku_packing_lists set status='sent' where id=(select pl from sh_ids);
select is((select array_agg(to_status order by changed_at,id) from romiku_status_history where resource_id=(select pl from sh_ids)),array['draft','incomplete','draft','completed','sent'],'Packing repeated states retained');
select is((select count(*) from romiku_status_history where resource_id=(select pi from sh_ids)),2::bigint,'PI transition recorded');
select is((select count(*) from romiku_status_history where resource_id=(select out from sh_ids)),2::bigint,'Outbound transition recorded');
update romiku_orders set archived_at=now() where id=(select o from sh_ids);
select is((select count(*) from romiku_status_history where resource_id=(select o from sh_ids)),1::bigint,'archive is not a business status');
update romiku_orders set archived_at=null where id=(select o from sh_ids);
-- Cursor paging, labels view, and limits all execute as caller.
create temporary table sh_page as select romiku_get_status_history('quote',(select q from sh_ids),2) response;
select is(jsonb_array_length((select response->'records' from sh_page)),2,'history page size enforced before returning');
select is((select response->>'has_more' from sh_page),'true','history has_more independent of UI');
select is((romiku_get_status_history('quote',(select q from sh_ids),2,((select response#>>'{next_cursor,changed_at}' from sh_page))::timestamptz,((select response#>>'{next_cursor,id}' from sh_page))::uuid)->'records'->0->>'to_status'),'customer_no_reply','next cursor continues without duplicates');
select throws_ok($$select romiku_get_status_history('payments',(select q from sh_ids))$$,'22023',null,'fixed history resource whitelist excludes Payment');
select throws_ok($$select romiku_get_status_history('quote',(select q from sh_ids),101)$$,'22023',null,'history page bounded');
select throws_ok($$select romiku_get_status_history('quote',(select q from sh_ids),20,now(),null)$$,'22023',null,'partial cursor rejected');
select is(romiku_delete_record('order',(select o from sh_ids))->>'ok','true','draft Order controlled cascade still works');
select is((select count(*) from romiku_status_history where resource_id in (select o from sh_ids union select p from sh_ids)),0::bigint,'Order and Production child histories cleaned');
update romiku_pis set source_quote_id=(select q from sh_ids) where id=(select pi from sh_ids);
select is(romiku_delete_record('quote',(select q from sh_ids))->>'code','HAS_DOWNSTREAM','dependent Quote delete blocked');
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),6::bigint,'blocked delete retains history');
select is(romiku_batch_delete('packing',array[(select pl from sh_ids)])->'succeeded'->0->>'id',(select pl::text from sh_ids),'bulk controlled delete successful');
select is((select count(*) from romiku_status_history where resource_id=(select pl from sh_ids)),0::bigint,'bulk delete history cleanup');
select is((select status_changed_at from romiku_quote_totals where id=(select q from sh_ids)),(select status_changed_at from romiku_quotes where id=(select q from sh_ids)),'totals exposes timestamp');
savepoint revert_status;
update romiku_quotes set status='invalid' where id=(select q from sh_ids);
rollback to revert_status;
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),6::bigint,'transaction rollback includes history');
reset role;
create policy sh_hidden_parent on romiku_quotes as restrictive for select to authenticated using (notes <> 'unrelated');
set local role authenticated;
select is((select count(*) from romiku_status_history where resource_id=(select q from sh_ids)),0::bigint,'history read respects parent RLS');
select is(jsonb_array_length(romiku_get_status_history('quote',(select q from sh_ids))->'records'),0,'RPC respects parent RLS');
reset role;
set local role anon;
select throws_ok($$select * from public.romiku_status_history$$,'42501',null,'anon cannot read history');
select throws_ok($$select * from public.romiku_status_history_display$$,'42501',null,'anon cannot read display view');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role service_role;
create temporary table sh_system as select gen_random_uuid() id;
insert into romiku_outbound_companies(id,name) select id,'System history QA' from sh_system;
update romiku_outbound_companies set status='contacted' where id=(select id from sh_system);
select is((select change_source from romiku_status_history where resource_id=(select id from sh_system) order by changed_at desc,id desc limit 1),'system','system change explicitly attributed');
select is((select changed_by from romiku_status_history where resource_id=(select id from sh_system) order by changed_at desc,id desc limit 1),null::uuid,'system actor remains NULL');
reset role;
select is((select prosecdef from pg_proc where oid='public.romiku_get_status_history(text,uuid,integer,timestamptz,uuid)'::regprocedure),false,'history RPC invoker');
select ok(not has_function_privilege('authenticated','public.romiku_record_status_history()','execute'),'client cannot invoke history writer');
select ok(not has_function_privilege('anon','public.romiku_get_status_history(text,uuid,integer,timestamptz,uuid)','execute'),'anon cannot execute history RPC');
drop policy sh_hidden_parent on romiku_quotes;
set local role authenticated;
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select romiku_get_status_history('quote',(select q from sh_ids))$$,'42501',null,'history requires auth uid');
select throws_ok($$update romiku_quotes set status='quoted' where id=(select q from sh_ids)$$,'42501',null,'status writing requires auth uid');
reset role;
select * from finish();
rollback;
