begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_column('public','romiku_formal_customers','marking_profile','Customer owns marking defaults');
select has_column('public','romiku_production_orders','marking_snapshot','Production owns marking snapshot');
select has_column('public','romiku_production_items','position','Production items have saved stable positions');
select is((select public from storage.buckets where id='romiku-marking-assets'),false,'marking assets are private');
insert into auth.users(id,email,raw_user_meta_data) values ('de400000-0000-0000-0000-000000000001','production-marking-test@example.test','{}');
create temporary table marking_ids(kind text primary key,id uuid default gen_random_uuid());
insert into marking_ids(kind) values ('customer'),('order'),('item'),('production');
grant all on marking_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','de400000-0000-0000-0000-000000000001',true);
insert into romiku_formal_customers(id,name,marking_profile) select id,'Marking customer','{"version":1,"front_mark":{"mode":"text","text":"ORIGINAL FRONT"}}'::jsonb from marking_ids where kind='customer';
insert into romiku_orders(id,formal_customer_id) select id,(select id from marking_ids where kind='customer') from marking_ids where kind='order';
insert into romiku_order_items(id,order_id,sku,quantity,product_snapshot) select id,(select id from marking_ids where kind='order'),'SUN5',160,'{"name":"Saved Lamp","specification":"48W"}'::jsonb from marking_ids where kind='item';
insert into romiku_production_orders(id,order_id,marking_snapshot) select id,(select id from marking_ids where kind='order'),'{"version":1,"front_mark":{"mode":"text","text":"ORIGINAL FRONT"},"labeling_requirements":"Historical label","production_requirements":"Historical requirement"}'::jsonb from marking_ids where kind='production';
insert into romiku_production_items(production_order_id,order_id,source_order_item_id,sku,quantity,position,packaging_snapshot,product_snapshot) select (select id from marking_ids where kind='production'),(select id from marking_ids where kind='order'),id,'SUN5',150,1,'{"cartons":5,"qty_per_carton":32}'::jsonb,'{"name":"Saved Lamp","specification":"48W"}'::jsonb from marking_ids where kind='item';
select is((select quantity from romiku_production_items where production_order_id=(select id from marking_ids where kind='production')),150::numeric,'quantity independent of cartons times qty per carton');
update romiku_formal_customers set marking_profile='{"front_mark":{"mode":"text","text":"NEW FRONT"}}' where id=(select id from marking_ids where kind='customer');
update romiku_order_items set product_snapshot='{"name":"New name"}' where id=(select id from marking_ids where kind='item');
update romiku_orders set notes='New Order requirements' where id=(select id from marking_ids where kind='order');
select is((select marking_snapshot#>>'{front_mark,text}' from romiku_production_orders where id=(select id from marking_ids where kind='production')),'ORIGINAL FRONT','customer change does not alter Production');
select is((select marking_snapshot->>'production_requirements' from romiku_production_orders where id=(select id from marking_ids where kind='production')),'Historical requirement','Order changes do not alter requirements');
select is((select product_snapshot->>'name' from romiku_production_items where production_order_id=(select id from marking_ids where kind='production')),'Saved Lamp','source item change does not alter saved product');
update romiku_production_orders set marking_snapshot=jsonb_set(marking_snapshot,'{front_mark,text}','"Production only"') where id=(select id from marking_ids where kind='production');
select is((select marking_profile#>>'{front_mark,text}' from romiku_formal_customers where id=(select id from marking_ids where kind='customer')),'NEW FRONT','Production edits do not write back');
select ok((romiku_global_search('NEW FRONT',array['formal_customer'],5,0,'{}')->'groups'->0->>'total_count')::int>=1,'customer marking text is indexed and searchable');
select ok((romiku_global_search('Historical label',array['production'],5,0,'{}')->'groups'->0->>'total_count')::int>=1,'Production labeling text is searchable');
insert into storage.objects(bucket_id,name) values ('romiku-marking-assets','de400000-0000-0000-0000-000000000001/original.png');
select is((select count(*) from storage.objects where bucket_id='romiku-marking-assets' and name='de400000-0000-0000-0000-000000000001/original.png'),1::bigint,'authenticated can upload/read own immutable marking asset');
update storage.objects set name='overwrite.png' where bucket_id='romiku-marking-assets' and name='de400000-0000-0000-0000-000000000001/original.png';
-- Simulate the Storage API's transaction-local delete setting; RLS must still deny rows.
select set_config('storage.allow_delete_query','true',true);
delete from storage.objects where bucket_id='romiku-marking-assets' and name='de400000-0000-0000-0000-000000000001/original.png';
select is((select count(*) from storage.objects where bucket_id='romiku-marking-assets' and name='de400000-0000-0000-0000-000000000001/original.png'),1::bigint,'authenticated cannot overwrite or delete historical assets');
select throws_ok($$insert into storage.objects(bucket_id,name) values ('romiku-marking-assets','another-user/forbidden.png')$$,'42501',null,'uploads require user folder');
set local role anon;
select is((select count(*) from storage.objects where bucket_id='romiku-marking-assets'),0::bigint,'anon cannot read private marking objects');
select throws_ok($$insert into storage.objects(bucket_id,name) values ('romiku-marking-assets','de400000-0000-0000-0000-000000000001/anon.png')$$,'42501',null,'anon cannot upload');
reset role;
select * from finish();
rollback;
