begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values('de700000-0000-0000-0000-000000000001','allocation@example.test','{}');
create temporary table cap_ids(kind text primary key,id uuid default gen_random_uuid());
insert into cap_ids(kind) values('order'),('source'),('p1'),('p2'),('i1'),('i2');
grant all on cap_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','de700000-0000-0000-0000-000000000001',true);
insert into romiku_orders(id) select id from cap_ids where kind='order';
insert into romiku_order_items(id,order_id,sku,quantity) select s.id,o.id,'SUN5',100 from cap_ids s,cap_ids o where s.kind='source' and o.kind='order';
insert into romiku_production_orders(id,order_id) select p.id,o.id from cap_ids p,cap_ids o where p.kind in ('p1','p2') and o.kind='order';
insert into romiku_production_items(id,production_order_id,order_id,source_order_item_id,sku,quantity) select i.id,p.id,o.id,s.id,'SUN5',case when i.kind='i1' then 60 else 40 end from cap_ids i,cap_ids p,cap_ids o,cap_ids s where ((i.kind='i1' and p.kind='p1') or (i.kind='i2' and p.kind='p2')) and o.kind='order' and s.kind='source';
select throws_like($q$update romiku_production_items set quantity=41 where id=(select id from cap_ids where kind='i2')$q$,'%生产安排超过订单数量%','direct item update cannot exceed capacity');
select is((select quantity from romiku_production_items where id=(select id from cap_ids where kind='i2')),40::numeric,'failed direct write rolls back');
select throws_like($q$update romiku_order_items set quantity=99 where id=(select id from cap_ids where kind='source')$q$,'%已安排%','Order reduction cannot violate assigned quantity');
select has_function('public','romiku_production_allocations',array['uuid'],'server allocation query exists');
select is((select production_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),100::numeric,'sums multiple Productions');
select is((select unallocated_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),0::numeric,'fully assigned has zero remaining');
select is((select jsonb_array_length(allocations) from romiku_production_allocations((select id from cap_ids where kind='order'))),2,'allocations include both linked Production documents');
update romiku_production_orders set status='cancelled' where id=(select id from cap_ids where kind='p2');
select is((select unallocated_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),40::numeric,'cancellation releases exactly its quantity');
update romiku_production_items set quantity=80 where id=(select id from cap_ids where kind='i1');
select throws_like($q$update romiku_production_orders set status='pending' where id=(select id from cap_ids where kind='p2')$q$,'%生产安排超过订单数量%','cancelled restoration is guarded');
select is((select status from romiku_production_orders where id=(select id from cap_ids where kind='p2')),'cancelled','failed restoration keeps cancelled status');
update romiku_production_items set quantity=20 where id=(select id from cap_ids where kind='i2');
update romiku_production_orders set status='pending' where id=(select id from cap_ids where kind='p2');
select is((select unallocated_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),0::numeric,'restoration within capacity succeeds');
update romiku_production_orders set archived_at=now() where id=(select id from cap_ids where kind='p1');
select is((select production_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),100::numeric,'archived still counts, preserving existing semantics');
update romiku_production_orders set status='completed' where id=(select id from cap_ids where kind='p1');
select is((select production_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),100::numeric,'completed still counts');
reset role;
select is((select last_value from romiku_production_order_counters where order_id=(select id from cap_ids where kind='order')),2,'capacity locks do not increment or reclaim Pxx');
reset role;
select ok(not has_function_privilege('anon','public.romiku_production_allocations(uuid)','execute'),'anon cannot query allocations');
select is((select prosecdef from pg_proc where oid='public.romiku_production_allocations(uuid)'::regprocedure),false,'allocation RPC is invoker');
create policy cap_deny_order on romiku_order_items as restrictive for select to authenticated using(false);
set local role authenticated;
select is((select count(*) from romiku_production_allocations((select id from cap_ids where kind='order'))),0::bigint,'allocation query respects RLS');
reset role;
drop policy cap_deny_order on romiku_order_items;
-- Simulate a pre-migration excess, without any migration repairing data.
alter table romiku_production_items disable trigger romiku_production_item_capacity;
update romiku_production_items set quantity=120 where id=(select id from cap_ids where kind='i1');
alter table romiku_production_items enable trigger romiku_production_item_capacity;
set local role authenticated;
select lives_ok($q$update romiku_production_items set production_note_zh='repair later' where id=(select id from cap_ids where kind='i1')$q$,'legacy excess allows unrelated notes');
select lives_ok($q$update romiku_production_items set quantity=110 where id=(select id from cap_ids where kind='i1')$q$,'legacy excess can be reduced');
select throws_like($q$update romiku_production_items set quantity=111 where id=(select id from cap_ids where kind='i1')$q$,'%生产安排超过订单数量%','legacy excess cannot increase');
select is((select unallocated_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),(-30)::numeric,'legacy excess stays visible instead of silently rewritten');
-- Whole-session restoration validates the final quantities, not an intermediate state.
create function pg_temp.cap_expected(pid uuid) returns jsonb language sql as $$select jsonb_build_object('header_updated_at',p.updated_at,'items',(select jsonb_agg(jsonb_build_object('id',i.id,'updated_at',i.updated_at)) from romiku_production_items i where i.production_order_id=p.id)) from romiku_production_orders p where p.id=pid$$;
create function pg_temp.cap_items(pid uuid,qty numeric) returns jsonb language sql as $$select jsonb_agg(jsonb_build_object('id',i.id,'source_order_item_id',i.source_order_item_id,'quantity',qty,'product_snapshot','{}'::jsonb,'packaging_snapshot','{}'::jsonb,'marking_override',i.marking_override)) from romiku_production_items i where i.production_order_id=pid$$;
update romiku_production_orders set status='cancelled' where id=(select id from cap_ids where kind='p1');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending"}',pg_temp.cap_items(p.id,80),pg_temp.cap_expected(p.id))->>'ok','true','atomic reduction and restoration uses final quantity') from romiku_production_orders p where id=(select id from cap_ids where kind='p1');
select is((select production_quantity from romiku_production_allocations((select id from cap_ids where kind='order'))),100::numeric,'atomic restoration preserves capacity');
update romiku_production_orders set status='cancelled' where id=(select id from cap_ids where kind='p2');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending","notes":"should roll back"}',pg_temp.cap_items(p.id,40),pg_temp.cap_expected(p.id))->>'code','OVER_ASSIGNED','workspace restoration cannot exceed capacity') from romiku_production_orders p where id=(select id from cap_ids where kind='p2');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending"}',pg_temp.cap_items(p.id,40),pg_temp.cap_expected(p.id))#>>'{dependencies,0,other_quantity}','80.0000','blocker reports other allocations') from romiku_production_orders p where id=(select id from cap_ids where kind='p2');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending"}',pg_temp.cap_items(p.id,40),pg_temp.cap_expected(p.id))#>>'{dependencies,0,this_quantity}','40','blocker reports proposed document quantity') from romiku_production_orders p where id=(select id from cap_ids where kind='p2');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending"}',pg_temp.cap_items(p.id,40),pg_temp.cap_expected(p.id))#>>'{dependencies,0,excess_quantity}','20.0000','blocker reports exact excess') from romiku_production_orders p where id=(select id from cap_ids where kind='p2');
select is(romiku_save_production_workspace(p.id,p.order_id,'{"status":"pending"}',pg_temp.cap_items(p.id,40),pg_temp.cap_expected(p.id))#>>'{dependencies,0,allocations,0,id}',(select id::text from cap_ids where kind='p1'),'blocker links occupying Production') from romiku_production_orders p where id=(select id from cap_ids where kind='p2');
select is((select status from romiku_production_orders where id=(select id from cap_ids where kind='p2')),'cancelled','rejected workspace preserves header');
select is((select quantity from romiku_production_items where id=(select id from cap_ids where kind='i2')),20::numeric,'rejected workspace preserves item');
select set_config('request.jwt.claim.sub','',true);
select throws_ok($q$select * from romiku_production_allocations((select id from cap_ids where kind='order'))$q$,'42501','请先登录。','uid required');
reset role;
select * from finish();
rollback;
