begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select has_column('public','romiku_orders','production_defaults_snapshot','Order has independent production defaults');
select has_column('public','romiku_production_items','marking_override','Item has independent override');
insert into auth.users(id,email,raw_user_meta_data) values ('de500000-0000-0000-0000-000000000001','instruction-test@example.test','{}');
create temporary table instruction_ids(kind text primary key,id uuid default gen_random_uuid());
insert into instruction_ids(kind) values ('customer'),('order'),('order2'),('item'),('production'),('production2'),('line'),('line2'),('quote');
grant all on instruction_ids to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','de500000-0000-0000-0000-000000000001',true);
insert into romiku_formal_customers(id,name,marking_profile) select id,'Instructions customer','{"version":1,"front_mark":{"mode":"image","image_asset":{"bucket":"romiku-marking-assets","path":"old/front.png"}},"small_label":{"mode":"text","text":"Made in China"},"production_requirements":"Protect cartons"}'::jsonb from instruction_ids where kind='customer';
insert into romiku_orders(id,formal_customer_id,notes) select id,(select id from instruction_ids where kind='customer'),'Saved Order note' from instruction_ids where kind='order';
select is((select production_defaults_snapshot#>>'{small_label,text}' from romiku_orders where id=(select id from instruction_ids where kind='order')),'Made in China','new Order copies customer defaults');
select ok((select production_defaults_snapshot->>'initialized_at' is not null from romiku_orders where id=(select id from instruction_ids where kind='order')),'initialization is explicit');
update romiku_formal_customers set marking_profile='{"small_label":{"mode":"text","text":"Changed customer"}}' where id=(select id from instruction_ids where kind='customer');
select is((select production_defaults_snapshot#>>'{small_label,text}' from romiku_orders where id=(select id from instruction_ids where kind='order')),'Made in China','customer edits do not mutate saved Order');
select is((select production_defaults_snapshot#>>'{front_mark,image_asset,path}' from romiku_orders where id=(select id from instruction_ids where kind='order')),'old/front.png','old asset reference stays stable');
insert into romiku_orders(id,notes) select id,'Legacy saved note' from instruction_ids where kind='order2';
select is(public.romiku_build_instruction_snapshot('{"small_label":{"mode":"none"}}','Saved legacy note','legacy_order',null)->>'production_requirements','Saved legacy note','legacy builder uses saved fields only');
insert into romiku_order_items(id,order_id,sku,quantity) select id,(select id from instruction_ids where kind='order'),'SUN5',160 from instruction_ids where kind='item';
insert into romiku_production_orders(id,order_id,marking_snapshot) select ids.id,o.id,o.production_defaults_snapshot from instruction_ids ids cross join romiku_orders o where ids.kind in ('production','production2') and o.id=(select id from instruction_ids where kind='order');
insert into romiku_production_items(id,production_order_id,order_id,source_order_item_id,sku,quantity) select id,(select id from instruction_ids where kind=case when ids.kind='line' then 'production' else 'production2' end),(select id from instruction_ids where kind='order'),(select id from instruction_ids where kind='item'),'SUN5',10 from instruction_ids ids where kind in ('line','line2');
select is((select marking_override->>'mode' from romiku_production_items where id=(select id from instruction_ids where kind='line')),'inherit','items default to compact inherit');
select is(public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'add','{"labels":[{"type":"barcode","mode":"text","text":"Barcode"}]}'),1,'authenticated batch add succeeds');
select is((select marking_override->>'mode' from romiku_production_items where id=(select id from instruction_ids where kind='line')),'append','adding to inherit becomes append');
select throws_ok($$select public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line'),(select id from instruction_ids where kind='line2')],'reset','{}')$$,'23514',null,'cross-production batch rejected atomically');
select is((select marking_override->>'mode' from romiku_production_items where id=(select id from instruction_ids where kind='line')),'append','rejected batch leaves valid item unchanged');
select is(public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'set','{"mode":"replace","labels":[{"mode":"text","text":"Private label"}]}'),1,'replace saved');
select is(public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'add','{"labels":[{"mode":"text","text":"Warning"}]}'),1,'add works on replace');
select is((select marking_override->>'mode' from romiku_production_items where id=(select id from instruction_ids where kind='line')),'replace','batch add does not reintroduce common labels for replace');
select is((select jsonb_array_length(marking_override->'labels') from romiku_production_items where id=(select id from instruction_ids where kind='line')),2,'both custom labels retained');
update romiku_orders set production_defaults_snapshot=public.romiku_build_instruction_snapshot('{}','Order B','manual',null) where id=(select id from instruction_ids where kind='order');
select isnt((select marking_snapshot->>'production_requirements' from romiku_production_orders where id=(select id from instruction_ids where kind='production')),'Order B','Order update does not auto-sync Production');
select is(public.romiku_reload_production_defaults((select id from instruction_ids where kind='production'))->>'production_requirements','Order B','explicit reload copies saved Order');
select is((select marking_override->>'mode' from romiku_production_items where id=(select id from instruction_ids where kind='line')),'replace','reload preserves item override');
select isnt((select marking_snapshot->>'production_requirements' from romiku_production_orders where id=(select id from instruction_ids where kind='production2')),'Order B','reload does not modify sibling Production');
update romiku_orders set production_defaults_snapshot=public.romiku_build_instruction_snapshot('{}','','manual',null),notes='Later note' where id=(select id from instruction_ids where kind='order');
select is((select production_defaults_snapshot->>'production_requirements' from romiku_orders where id=(select id from instruction_ids where kind='order')),'','explicit clear is not auto-filled');
select throws_ok($$update romiku_production_items set marking_override='{"mode":"invalid"}' where id=(select id from instruction_ids where kind='line')$$,'23514',null,'invalid mode rejected');
select throws_ok($$select public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'drop','{}')$$,'23514',null,'action whitelist enforced');
insert into romiku_quotes(id,formal_customer_id) select id,(select id from instruction_ids where kind='customer') from instruction_ids where kind='quote';
insert into instruction_ids values ('converted',public.romiku_convert_document('quote',(select id from instruction_ids where kind='quote'),'order'));
select is((select production_defaults_snapshot#>>'{small_label,text}' from romiku_orders where id=(select id from instruction_ids where kind='converted')),'Changed customer','converted Order initialized at creation');
reset role;
select is((select prosecdef from pg_proc where oid='public.romiku_update_item_marking(uuid,uuid[],text,jsonb)'::regprocedure),false,'batch RPC is SECURITY INVOKER');
select is((select prosecdef from pg_proc where oid='public.romiku_reload_production_defaults(uuid)'::regprocedure),false,'reload RPC is SECURITY INVOKER');
select ok(not has_function_privilege('anon','public.romiku_update_item_marking(uuid,uuid[],text,jsonb)','execute'),'anon cannot batch write');
select ok(not has_function_privilege('anon','public.romiku_reload_production_defaults(uuid)','execute'),'anon cannot reload');

select throws_ok($$update romiku_orders set production_defaults_snapshot='{"initialized_at":"2026-10-04","source":{"kind":"manual"}}' where id=(select id from instruction_ids where kind='order')$$,'23514',null,'missing schema version cannot masquerade as initialized');
select is(public.romiku_valid_item_marking('{"mode":"replace","labels":[{"mode":"image","image_asset":{"bucket":"other","path":"x.png"}}]}'),false,'foreign bucket rejected');
select is(public.romiku_valid_item_marking('{"mode":"append","labels":{}}'),false,'non-array labels rejected');
select is(public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'set','{"mode":"inherit","labels":[{"text":"stale"}]}'),1,'inherit discards inactive overrides');
select is((select marking_override from romiku_production_items where id=(select id from instruction_ids where kind='line')),'{"mode":"inherit"}'::jsonb,'inherit remains a reference, not copied labels');
select set_config('request.jwt.claim.sub','',true);
select throws_ok($$select public.romiku_reload_production_defaults((select id from instruction_ids where kind='production'))$$,'42501',null,'authenticated role without uid cannot reload');
select throws_ok($$select public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line')],'reset','{}')$$,'42501',null,'authenticated role without uid cannot batch edit');
select set_config('request.jwt.claim.sub','de500000-0000-0000-0000-000000000001',true);
insert into instruction_ids(kind) values ('line3');
insert into romiku_production_items(id,production_order_id,order_id,source_order_item_id,sku,quantity) select id,(select id from instruction_ids where kind='production'),(select id from instruction_ids where kind='order'),(select id from instruction_ids where kind='item'),'SUN5',10 from instruction_ids where kind='line3';
reset role;
create policy instruction_test_restrict_update on romiku_production_items as restrictive for update to authenticated using (id<>(select id from instruction_ids where kind='line3'));
set local role authenticated;
select throws_ok($$select public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line'),(select id from instruction_ids where kind='line3')],'add','{"labels":[{"text":"Must rollback"}]}')$$,'23514',null,'RLS denies the whole batch before writes');
select is((select marking_override from romiku_production_items where id=(select id from instruction_ids where kind='line')),'{"mode":"inherit"}'::jsonb,'permitted row update also rolled back');
reset role;
drop policy instruction_test_restrict_update on romiku_production_items;
create function pg_temp.reject_instruction_update() returns trigger language plpgsql as $$begin if new.id=(select id from instruction_ids where kind='line3') then raise exception 'test late failure' using errcode='23514'; end if;return new;end$$;
create trigger instruction_test_late_failure before update on romiku_production_items for each row execute function pg_temp.reject_instruction_update();
set local role authenticated;
select throws_ok($$select public.romiku_update_item_marking((select id from instruction_ids where kind='production'),array[(select id from instruction_ids where kind='line'),(select id from instruction_ids where kind='line3')],'add','{"labels":[{"text":"Must rollback"}]}')$$,'23514',null,'late write failure aborts batch');
select is((select marking_override from romiku_production_items where id=(select id from instruction_ids where kind='line')),'{"mode":"inherit"}'::jsonb,'late failure leaves no partially written labels');
reset role;
drop trigger instruction_test_late_failure on romiku_production_items;
create policy instruction_test_restrict_read on romiku_orders as restrictive for select to authenticated using (id<>(select id from instruction_ids where kind='order'));
set local role authenticated;
select throws_ok($$select public.romiku_reload_production_defaults((select id from instruction_ids where kind='production'))$$,'42501',null,'reload respects source Order RLS');
reset role;
drop policy instruction_test_restrict_read on romiku_orders;

select * from finish();
rollback;
