begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values ('de100000-0000-0000-0000-000000000001','delete-test@example.test','{}');
select ok(has_function_privilege('authenticated','public.romiku_delete_record(text,uuid)','execute'),'authenticated can call');
select ok(not has_function_privilege('anon','public.romiku_delete_record(text,uuid)','execute'),'anon cannot call');
select ok(prosecdef and proconfig @> array['search_path=""'], 'security definer and fixed empty search path') from pg_proc where oid='public.romiku_delete_record(text,uuid)'::regprocedure;
set local role anon;
select throws_ok($$select romiku_delete_record('quote',gen_random_uuid())$$,'42501',null,'anon RPC denied');
reset role;
set local role authenticated;
select is(romiku_delete_record('quote',gen_random_uuid())->>'code','UNAUTHENTICATED','missing user denied');
select set_config('request.jwt.claim.sub','de100000-0000-0000-0000-000000000001',true);
select is(romiku_delete_record(null,gen_random_uuid())->>'code','UNSUPPORTED_KIND','null kind rejected');
select is(romiku_delete_record('romiku_quotes;delete',gen_random_uuid())->>'code','UNSUPPORTED_KIND','untrusted kind rejected');
select is(romiku_delete_record('quote',gen_random_uuid())->>'code','NOT_FOUND','missing quote');
select throws_ok($$delete from romiku_quotes where false$$,'42501',null,'direct quote header delete denied');
select is(romiku_delete_record('pi',gen_random_uuid())->>'code','NOT_FOUND','missing pi');
select throws_ok($$delete from romiku_pis where false$$,'42501',null,'direct pi header delete denied');
select is(romiku_delete_record('order',gen_random_uuid())->>'code','NOT_FOUND','missing order');
select throws_ok($$delete from romiku_orders where false$$,'42501',null,'direct order header delete denied');
select is(romiku_delete_record('packing',gen_random_uuid())->>'code','NOT_FOUND','missing packing');
select throws_ok($$delete from romiku_packing_lists where false$$,'42501',null,'direct packing header delete denied');
select is(romiku_delete_record('outbound',gen_random_uuid())->>'code','NOT_FOUND','missing outbound');
select throws_ok($$delete from romiku_outbound_companies where false$$,'42501',null,'direct outbound header delete denied');
select is(romiku_delete_record('manual_task',gen_random_uuid())->>'code','NOT_FOUND','missing manual_task');
create temporary table ids(kind text primary key,id uuid default gen_random_uuid());
insert into ids(kind) values ('quote'),('pi'),('order'),('packing'),('outbound'),('manual_task');
insert into romiku_quotes(id) select id from ids where kind='quote';
insert into romiku_quote_items(quote_id,sku,quantity) select id,'DELETE-SKU',10 from ids where kind='quote';
select romiku_publish_quote_version((select id from ids where kind='quote'));
insert into romiku_manual_tasks(title,notes,quote_id) select 'keep quote task','keep content',id from ids where kind='quote';
insert into romiku_pis(id,source_quote_id) values ((select id from ids where kind='pi'),(select id from ids where kind='quote'));
insert into romiku_pi_items(pi_id,sku,quantity) select id,'DELETE-SKU',10 from ids where kind='pi';
insert into romiku_orders(id,source_pi_id,source_quote_id) values ((select id from ids where kind='order'),(select id from ids where kind='pi'),(select id from ids where kind='quote'));
insert into romiku_order_items(order_id,sku,quantity) select id,'DELETE-SKU',10 from ids where kind='order';
select is(romiku_delete_record('quote',(select id from ids where kind='quote'))->>'code','HAS_DOWNSTREAM','quote blocked by PI/order');
select is(romiku_delete_record('pi',(select id from ids where kind='pi'))->>'code','HAS_DOWNSTREAM','PI blocked by order');
insert into romiku_production_orders(order_id) select id from ids where kind='order';
insert into romiku_production_orders(order_id) select id from ids where kind='order';
insert into romiku_packing_lists(id,order_id) values ((select id from ids where kind='packing'),(select id from ids where kind='order'));
insert into romiku_packing_items(packing_list_id,order_id,source_order_item_id,sku,quantity) select (select id from ids where kind='packing'),order_id,id,sku,4 from romiku_order_items where order_id=(select id from ids where kind='order');
insert into romiku_payments(order_id,kind,amount) select id,'deposit',1 from ids cross join generate_series(1,3) where kind='order';
select is(romiku_delete_record('order',(select id from ids where kind='order'))->'dependencies','{"production":2,"packing":1,"payments":3}'::jsonb,'exact downstream counts');
select is(romiku_delete_record('order',(select id from ids where kind='order'))->>'message','该订单已有 2 张生产单、1 张装箱单、3 条收款记录，无法删除。','readable dependency message');
select is(romiku_delete_record('packing',(select id from ids where kind='packing')),'{"ok":true}'::jsonb,'packing deleted');
select is((select remaining_quantity from romiku_order_item_remaining where order_id=(select id from ids where kind='order')),10::numeric,'packing delete restores order remaining');
select is((select count(*) from romiku_packing_items where packing_list_id=(select id from ids where kind='packing')),0::bigint,'packing children removed');
reset role;
delete from romiku_production_orders where order_id=(select id from ids where kind='order');
delete from romiku_payments where order_id=(select id from ids where kind='order');
set local role authenticated;
insert into romiku_manual_tasks(title,order_id) select 'keep order task',id from ids where kind='order';
select is(romiku_delete_record('order',(select id from ids where kind='order')),'{"ok":true}'::jsonb,'order and internal counter deleted');
select ok(exists(select 1 from romiku_pis where id=(select id from ids where kind='pi')) and exists(select 1 from romiku_quotes where id=(select id from ids where kind='quote')),'source PI and quote retained');
select ok(exists(select 1 from romiku_manual_tasks where title='keep order task' and order_id is null),'order task detached');
insert into romiku_manual_tasks(title,pi_id) select 'keep PI task',id from ids where kind='pi';
select is(romiku_delete_record('pi',(select id from ids where kind='pi')),'{"ok":true}'::jsonb,'PI deleted');
select ok(exists(select 1 from romiku_manual_tasks where title='keep PI task' and pi_id is null),'PI task detached');
-- A late failure must roll back task unlinking and item/version deletes.
reset role;
create function public.delete_test_fail() returns trigger language plpgsql as $$ begin raise exception 'private FK detail'; end $$;
create trigger delete_test_fail before delete on romiku_quotes for each row execute function public.delete_test_fail();
set local role authenticated;
select is(romiku_delete_record('quote',(select id from ids where kind='quote'))->>'code','DELETE_FAILED','late delete failure is structured');
select ok(exists(select 1 from romiku_manual_tasks where title='keep quote task' and quote_id=(select id from ids where kind='quote')),'rollback restores task link');
select is((select count(*) from romiku_quote_items where quote_id=(select id from ids where kind='quote')),1::bigint,'rollback restores items');
select is((select count(*) from romiku_quote_versions where quote_id=(select id from ids where kind='quote')),1::bigint,'rollback restores versions');
reset role;
drop trigger delete_test_fail on romiku_quotes;
set local role authenticated;
select is(romiku_delete_record('quote',(select id from ids where kind='quote')),'{"ok":true}'::jsonb,'quote including immutable versions deleted');
select ok(exists(select 1 from romiku_manual_tasks where title='keep quote task' and notes='keep content' and quote_id is null),'quote task content preserved');
select is((select count(*) from romiku_quote_versions where quote_id=(select id from ids where kind='quote')),0::bigint,'quote versions removed');
insert into romiku_outbound_companies(id,name) select id,'Delete test' from ids where kind='outbound';
insert into romiku_outbound_contacts(outbound_company_id,name) select id,'Contact' from ids where kind='outbound';
insert into romiku_outbound_followups(outbound_company_id,method,summary) select id,'email','Followup' from ids where kind='outbound';
insert into romiku_source_urls(outbound_company_id,source_type,url) select id,'website','https://example.test' from ids where kind='outbound';
insert into romiku_formal_customers(name,source_outbound_company_id) select 'keep customer',id from ids where kind='outbound';
insert into romiku_website_inquiries(customer_name,email,outbound_company_id) select 'keep inquiry','delete@example.test',id from ids where kind='outbound';
insert into romiku_quotes(id,outbound_company_id) values ((select id from ids where kind='quote'),(select id from ids where kind='outbound'));
insert into romiku_pis(id,outbound_company_id) values ((select id from ids where kind='pi'),(select id from ids where kind='outbound'));
insert into romiku_orders(id,outbound_company_id) values ((select id from ids where kind='order'),(select id from ids where kind='outbound'));
insert into romiku_manual_tasks(id,title,outbound_company_id) values ((select id from ids where kind='manual_task'),'keep outbound task',(select id from ids where kind='outbound'));
select is(romiku_delete_record('outbound',(select id from ids where kind='outbound')),'{"ok":true}'::jsonb,'outbound deleted');
select ok(exists(select 1 from romiku_formal_customers where name='keep customer' and source_outbound_company_id is null),'outbound retains formal_customers');
select ok(exists(select 1 from romiku_website_inquiries where customer_name='keep inquiry' and outbound_company_id is null),'outbound retains website_inquiries');
select ok(exists(select 1 from romiku_quotes where id=(select id from ids where kind='quote') and outbound_company_id is null),'outbound retains quotes');
select ok(exists(select 1 from romiku_pis where id=(select id from ids where kind='pi') and outbound_company_id is null),'outbound retains pis');
select ok(exists(select 1 from romiku_orders where id=(select id from ids where kind='order') and outbound_company_id is null),'outbound retains orders');
select ok(exists(select 1 from romiku_manual_tasks where id=(select id from ids where kind='manual_task') and outbound_company_id is null),'outbound retains manual_tasks');
select is((select count(*) from romiku_outbound_contacts where outbound_company_id=(select id from ids where kind='outbound')),0::bigint,'outbound removes outbound_contacts');
select is((select count(*) from romiku_outbound_followups where outbound_company_id=(select id from ids where kind='outbound')),0::bigint,'outbound removes outbound_followups');
select is((select count(*) from romiku_source_urls where outbound_company_id=(select id from ids where kind='outbound')),0::bigint,'outbound removes source_urls');
select is(romiku_delete_record('manual_task',(select id from ids where kind='manual_task')),'{"ok":true}'::jsonb,'manual task deleted');
select * from finish();
rollback;
